[project]
name = "dbt-goodparty"
version = "0.1.0"
description = "Data warehouse for GoodParty.org"
authors = [
    {name = "Hugh Karimi",email = "hussain.h.karimi@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas (>=2.2.3,<3.0.0)",
    "requests (>=2.32.3,<3.0.0)",
    "pyspark (>=3.5.5,<4.0.0)",
    "psycopg2 (>=2.9.10,<3.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false
