{% macro state_code_to_name(column_name) %}
    {#-
Returns full state name from a 2-letter state code.

Args:
    column_name: The column containing state codes (e.g., 'CA', 'NY')

Returns:
    Full state name (e.g., 'California', 'New York')
    Returns the original value if no match found.

Usage:
    {{ state_code_to_name('state_code') }} as state_name
-#}
    case
        upper(trim({{ column_name }}))
        when 'AK'
        then 'Alaska'
        when 'AL'
        then 'Alabama'
        when 'AR'
        then 'Arkansas'
        when 'AZ'
        then 'Arizona'
        when 'CA'
        then 'California'
        when 'CO'
        then 'Colorado'
        when 'CT'
        then 'Connecticut'
        when 'DC'
        then 'District of Columbia'
        when 'DE'
        then 'Delaware'
        when 'FL'
        then 'Florida'
        when 'GA'
        then 'Georgia'
        when 'HI'
        then 'Hawaii'
        when 'IA'
        then 'Iowa'
        when 'ID'
        then 'Idaho'
        when 'IL'
        then 'Illinois'
        when 'IN'
        then 'Indiana'
        when 'KS'
        then 'Kansas'
        when 'KY'
        then 'Kentucky'
        when 'LA'
        then 'Louisiana'
        when 'MA'
        then 'Massachusetts'
        when 'MD'
        then 'Maryland'
        when 'ME'
        then 'Maine'
        when 'MI'
        then 'Michigan'
        when 'MN'
        then 'Minnesota'
        when 'MO'
        then 'Missouri'
        when 'MS'
        then 'Mississippi'
        when 'MT'
        then 'Montana'
        when 'NC'
        then 'North Carolina'
        when 'ND'
        then 'North Dakota'
        when 'NE'
        then 'Nebraska'
        when 'NH'
        then 'New Hampshire'
        when 'NJ'
        then 'New Jersey'
        when 'NM'
        then 'New Mexico'
        when 'NV'
        then 'Nevada'
        when 'NY'
        then 'New York'
        when 'OH'
        then 'Ohio'
        when 'OK'
        then 'Oklahoma'
        when 'OR'
        then 'Oregon'
        when 'PA'
        then 'Pennsylvania'
        when 'RI'
        then 'Rhode Island'
        when 'SC'
        then 'South Carolina'
        when 'SD'
        then 'South Dakota'
        when 'TN'
        then 'Tennessee'
        when 'TX'
        then 'Texas'
        when 'UT'
        then 'Utah'
        when 'VA'
        then 'Virginia'
        when 'VT'
        then 'Vermont'
        when 'WA'
        then 'Washington'
        when 'WI'
        then 'Wisconsin'
        when 'WV'
        then 'West Virginia'
        when 'WY'
        then 'Wyoming'
        else {{ column_name }}
    end
{% endmacro %}
