with
    source as (select * from {{ source("airbyte_source", "gp_api_db_outreach") }}),
    renamed as (
        select
            {{ adapter.quote("_airbyte_raw_id") }},
            {{ adapter.quote("_airbyte_extracted_at") }},
            {{ adapter.quote("_airbyte_meta") }},
            {{ adapter.quote("_airbyte_generation_id") }},
            {{ adapter.quote("id") }},
            {{ adapter.quote("date") }},
            {{ adapter.quote("name") }},
            {{ adapter.quote("error") }},
            {{ adapter.quote("title") }},
            {{ adapter.quote("script") }},
            {{ adapter.quote("status") }},
            {{ adapter.quote("message") }},
            {{ adapter.quote("createdAt") }},
            {{ adapter.quote("did_state") }},
            {{ adapter.quote("image_url") }},
            {{ adapter.quote("updatedAt") }},
            {{ adapter.quote("campaignId") }},
            {{ adapter.quote("organization_slug") }},
            {{ adapter.quote("project_id") }},
            {{ adapter.quote("identity_id") }},
            {{ adapter.quote("outreach_type") }},
            {{ adapter.quote("phone_list_id") }},
            {{ adapter.quote("audience_request") }},
            {{ adapter.quote("voter_file_filter_id") }},
            {{ adapter.quote("denied_at") }},
            {{ adapter.quote("denied_by") }},
            {{ adapter.quote("text_count") }},
            {{ adapter.quote("approved_at") }},
            {{ adapter.quote("approved_by") }},
            {{ adapter.quote("archived_at") }},
            {{ adapter.quote("canceled_at") }},
            {{ adapter.quote("canceled_by") }},
            {{ adapter.quote("denied_reason") }},
            {{ adapter.quote("did_npa_subset") }},
            {{ adapter.quote("admin_edited_at") }},
            {{ adapter.quote("admin_edited_by") }},
            {{ adapter.quote("canceled_by_admin") }},
            {{ adapter.quote("billable_text_count") }},
            {{ adapter.quote("campaign_outreach_id") }},
            {{ adapter.quote("canvass_requested_at") }},
            {{ adapter.quote("scheduled_local_date") }},
            {{ adapter.quote("scheduled_local_time") }},
            {{ adapter.quote("phone_banking_list_id") }},
            {{ adapter.quote("campaign_plan_due_date") }},
            {{ adapter.quote("door_knocking_route_id") }},
            {{ adapter.quote("stripe_checkout_session_id") }}

        from source
    )
select *
from renamed
