with
    source as (select * from {{ source("airbyte_source", "stripe_api_charges") }}),
    renamed as (
        select
            {{ adapter.quote("_airbyte_raw_id") }},
            {{ adapter.quote("_airbyte_extracted_at") }},
            {{ adapter.quote("_airbyte_meta") }},
            {{ adapter.quote("_airbyte_generation_id") }},
            {{ adapter.quote("id") }},
            {{ adapter.quote("card") }},
            {{ adapter.quote("paid") }},
            {{ adapter.quote("order") }},
            {{ adapter.quote("amount") }},
            {{ adapter.quote("object") }},
            {{ adapter.quote("review") }},
            {{ adapter.quote("source") }},
            {{ adapter.quote("status") }},
            {{ adapter.quote("created") }},
            {{ adapter.quote("dispute") }},
            {{ adapter.quote("invoice") }},
            {{ adapter.quote("outcome") }},
            {{ adapter.quote("refunds") }},
            {{ adapter.quote("updated") }},
            {{ adapter.quote("captured") }},
            {{ adapter.quote("currency") }},
            {{ adapter.quote("customer") }},
            {{ adapter.quote("disputed") }},
            {{ adapter.quote("livemode") }},
            {{ adapter.quote("metadata") }},
            {{ adapter.quote("refunded") }},
            {{ adapter.quote("shipping") }},
            {{ adapter.quote("application") }},
            {{ adapter.quote("description") }},
            {{ adapter.quote("destination") }},
            {{ adapter.quote("receipt_url") }},
            {{ adapter.quote("failure_code") }},
            {{ adapter.quote("on_behalf_of") }},
            {{ adapter.quote("fraud_details") }},
            {{ adapter.quote("receipt_email") }},
            {{ adapter.quote("transfer_data") }},
            {{ adapter.quote("amount_updates") }},
            {{ adapter.quote("payment_intent") }},
            {{ adapter.quote("payment_method") }},
            {{ adapter.quote("receipt_number") }},
            {{ adapter.quote("transfer_group") }},
            {{ adapter.quote("amount_captured") }},
            {{ adapter.quote("amount_refunded") }},
            {{ adapter.quote("application_fee") }},
            {{ adapter.quote("billing_details") }},
            {{ adapter.quote("failure_message") }},
            {{ adapter.quote("source_transfer") }},
            {{ adapter.quote("balance_transaction") }},
            {{ adapter.quote("statement_descriptor") }},
            {{ adapter.quote("statement_description") }},
            {{ adapter.quote("application_fee_amount") }},
            {{ adapter.quote("payment_method_details") }},
            {{ adapter.quote("failure_balance_transaction") }},
            {{ adapter.quote("statement_descriptor_suffix") }},
            {{ adapter.quote("calculated_statement_descriptor") }}

        from source
    )
select *
from renamed
