with
    source as (
        select * from {{ source("airbyte_source", "stripe_api_subscriptions") }}
    ),
    renamed as (
        select
            {{ adapter.quote("_airbyte_raw_id") }},
            {{ adapter.quote("_airbyte_extracted_at") }},
            {{ adapter.quote("_airbyte_meta") }},
            {{ adapter.quote("_airbyte_generation_id") }},
            {{ adapter.quote("id") }},
            {{ adapter.quote("plan") }},
            {{ adapter.quote("items") }},
            {{ adapter.quote("object") }},
            {{ adapter.quote("status") }},
            {{ adapter.quote("billing") }},
            {{ adapter.quote("created") }},
            {{ adapter.quote("updated") }},
            {{ adapter.quote("currency") }},
            {{ adapter.quote("customer") }},
            {{ adapter.quote("discount") }},
            {{ adapter.quote("ended_at") }},
            {{ adapter.quote("livemode") }},
            {{ adapter.quote("metadata") }},
            {{ adapter.quote("quantity") }},
            {{ adapter.quote("schedule") }},
            {{ adapter.quote("cancel_at") }},
            {{ adapter.quote("trial_end") }},
            {{ adapter.quote("is_deleted") }},
            {{ adapter.quote("start_date") }},
            {{ adapter.quote("test_clock") }},
            {{ adapter.quote("application") }},
            {{ adapter.quote("canceled_at") }},
            {{ adapter.quote("description") }},
            {{ adapter.quote("tax_percent") }},
            {{ adapter.quote("trial_start") }},
            {{ adapter.quote("on_behalf_of") }},
            {{ adapter.quote("automatic_tax") }},
            {{ adapter.quote("transfer_data") }},
            {{ adapter.quote("days_until_due") }},
            {{ adapter.quote("default_source") }},
            {{ adapter.quote("latest_invoice") }},
            {{ adapter.quote("pending_update") }},
            {{ adapter.quote("trial_settings") }},
            {{ adapter.quote("invoice_settings") }},
            {{ adapter.quote("pause_collection") }},
            {{ adapter.quote("payment_settings") }},
            {{ adapter.quote("collection_method") }},
            {{ adapter.quote("default_tax_rates") }},
            {{ adapter.quote("billing_thresholds") }},
            {{ adapter.quote("current_period_end") }},
            {{ adapter.quote("billing_cycle_anchor") }},
            {{ adapter.quote("cancel_at_period_end") }},
            {{ adapter.quote("cancellation_details") }},
            {{ adapter.quote("current_period_start") }},
            {{ adapter.quote("pending_setup_intent") }},
            {{ adapter.quote("default_payment_method") }},
            {{ adapter.quote("application_fee_percent") }},
            {{ adapter.quote("billing_cycle_anchor_config") }},
            {{ adapter.quote("pending_invoice_item_interval") }},
            {{ adapter.quote("next_pending_invoice_item_invoice") }}

        from source
    )
select *
from renamed
