{#- Every source column must appear in exactly one list below; an unlisted
    column fails compilation so nothing reaches researchers unreviewed.
    Columns ending in _RETIRED are dropped: L2 nulls them out. -#}
{#- Direct identifiers and the retired DMA fields, removed entirely. VINs and
    IPs are dropped rather than hashed: their small key spaces make a hash
    reversible. Raw lender names can be a private seller's name; the
    standardized lender columns are kept. -#}
{%- set dropped = [
    "Landline_Phone_Number",
    "Cell_Phone",
    "Fname",
    "Mname",
    "Lname",
    "Name_Suffix",
    "House_Number",
    "Pre_Direction",
    "Street_Name",
    "Street_Suffix",
    "Post_Direction",
    "Unit_Designator_Number",
    "Primary_Address",
    "Secondary_Address",
    "Delivery_Point_Check_Digit",
    "DMA_Zone",
    "DMA_Code",
    "BirthDate",
    "DOB_Day",
    "LikelyRecentEmployment_Company_Name",
    "LikelyRecentEmployment_Physical_Address",
    "LikelyRecentEmployment_Mailing_Address",
    "LikelyRecentEmployment_Phone",
    "LikelyRecentEmployment_Email",
    "Auto_Vin_1",
    "Auto_Vin_2",
    "Auto_Vin_3",
    "Motorcycle_Vin_1",
    "IP1",
    "IP2",
    "IP3",
    "IP4",
    "IP5",
    "PreviousAddress_PrimaryAddress",
    "PreviousAddress_SecondaryAddress",
    "Legal_BriefDescription",
    "Home_Mortgage_Lender_Name",
    "Most_Recent_2nd_Lender_Name",
] -%}
{#- Unsalted SHA-256, so lalvoterid_hash equals voter_key in the voter marts. -#}
{%- set hashed_ids = [
    "Individual_Id",
    "Address_Id",
    "Family_Id",
    "Lalvoterid",
    "APN",
    "Placekey",
    "MAID1",
    "MAID2",
    "MAID3",
    "MAID4",
    "MAID5",
] -%}
{%- set y_flags = [
    "Registered_To_Vote",
    "Investments_Personal",
    "Single_Parent_in_Household",
    "Christian_Families",
    "Working_Woman",
    "African_American_Professional_in_Household",
    "SOHO_Indicator",
    "TV_Sat_Dish",
    "Presence_Of_CC",
    "Presence_Of_Gold_Plat_CC",
    "Presence_Of_Premium_CC",
    "Presence_Of_Upscale_Retail_CC",
    "Presence_Of_Bankcard",
    "Gas_Dept_Retail_CC",
    "American_Express_CC",
    "American_Express_Gold_Plat",
    "Discover_Gold_Premium",
    "Discover_Regular",
    "Gas_Retail_CC_Gold_Premium",
    "Mastercard_Gold_Premium",
    "Mastercard_Regular",
    "Visa_Gold_Premium",
    "Visa_Regular",
    "Travel_Entertainment_CC",
    "CC_Holder_Type_Unknown",
    "Children_in_HH_Age_00_02",
    "Children_in_HH_Age_00_02_Male",
    "Children_in_HH_Age_00_02_Female",
    "Children_in_HH_Age_00_02_Unknown",
    "Children_in_HH_Age_03_05",
    "Children_in_HH_Age_03_05_Male",
    "Children_in_HH_Age_03_05_Female",
    "Children_in_HH_Age_03_05_Unknown",
    "Children_in_HH_Age_06_10",
    "Children_in_HH_Age_06_10_Male",
    "Children_in_HH_Age_06_10_Female",
    "Children_in_HH_Age_06_10_Unknown",
    "Children_in_HH_Age_11_15",
    "Children_in_HH_Age_11_15_Male",
    "Children_in_HH_Age_11_15_Female",
    "Children_in_HH_Age_11_15_Unknown",
    "Children_in_HH_Age_16_17",
    "Children_in_HH_Age_16_17_Male",
    "Children_in_HH_Age_16_17_Female",
    "Children_in_HH_Age_16_17_Unknown",
    "Males_in_HH_18_24",
    "Females_in_HH_18_24",
    "Unknown_Gender_in_HH_18_24",
    "Males_in_HH_25_34",
    "Females_in_HH_25_34",
    "Unknown_Gender_in_HH_25_34",
    "Males_in_HH_35_44",
    "Females_in_HH_35_44",
    "Unknown_Gender_in_HH_35_44",
    "Males_in_HH_45_54",
    "Females_in_HH_45_54",
    "Unknown_Gender_in_HH_45_54",
    "Males_in_HH_55_64",
    "Females_in_HH_55_64",
    "Unknown_Gender_in_HH_55_64",
    "Males_in_HH_65_74",
    "Females_in_HH_65_74",
    "Unknown_Gender_in_HH_65_74",
    "Males_in_HH_75_Plus",
    "Females_in_HH_75_Plus",
    "Unknown_Gender_in_HH_75_Plus",
    "Young_Adult_In_HH",
    "Senior_Adult_In_HH",
    "Apparel_Childrens",
    "Apparel_Infant_Toddlers",
    "Apparel_Mens_Big_Tall",
    "Apparel_Mens",
    "Apparel_Petite",
    "Apparel_Womens",
    "Apparel_Womens_Plus_Size",
    "Apparel_Young_Mens",
    "Apparel_Young_Womens",
    "High_End_Appliances",
    "Music_Home_Stereo",
    "Arts_And_Antiques",
    "Arts_Art",
    "Theater_Performing_Arts",
    "Auto_Work",
    "Automotive_Buff",
    "Autoparts_Accessories",
    "Aviation_Int",
    "Books_Magazines",
    "Book_Buyer",
    "Book_Reader",
    "Books_Music_Books",
    "Books_Music_Audio",
    "Reading_General",
    "Reading_Mags",
    "Reading_Audio_Books",
    "Career_Int",
    "Pets_Cats",
    "Childrens_Babycare",
    "Childrens_Learning_Toys",
    "Childrens_Back_To_School",
    "Membership_Club",
    "Collectibles_Antiques",
    "Collectibles_Arts",
    "Collector_Avid",
    "Collectibles_Coins",
    "Collectibles_General",
    "Military_Memorabilia_Weapons",
    "Collectibles_Sports_Memorabilia",
    "Collectibles_Stamps",
    "Computer_Owner",
    "Consumer_Electronics",
    "Computer_Home_Office",
    "Electronics_Computers",
    "Cooking_Enthusiast",
    "Cooking_General",
    "Foods_Natural",
    "Cosmetics_Beauty",
    "Crafts_Hobbies_Buyer",
    "Craft_Int",
    "Pets_Dogs",
    "Do_It_Yourselfers_Typical_Choice",
    "DVD_Videos",
    "Education_Online",
    "High_Tech_Leader",
    "Exercise_Enthusiast",
    "Female_Merch_Buyer",
    "News_Financial",
    "Gaming_Int",
    "Games_Board_Puzzles",
    "Gaming_Casino",
    "Gardening",
    "Gardening_Farming_Buyer",
    "Golf_Enthusiast",
    "Collect_Special_Foods_Buyer",
    "Health_And_Beauty",
    "Exercise_Aerobic",
    "Exercise_Health_Grouping",
    "Exercise_Running_Jogging",
    "Exercise_Walking",
    "Dieting_Weightloss",
    "Health_Medical",
    "Self_Improvement",
    "Career_Improvement",
    "Home_Decor_Enthusiast",
    "Home_Improvement_Grouping",
    "Equestrian_Int",
    "House_Plants",
    "Investments_Foreign",
    "Investing_Finance_Grouping",
    "Investments_Realestate",
    "Invest_Stock_Securities",
    "Investments",
    "Invest_Active",
    "Jewelry_Buyer",
    "Common_Living",
    "Cultural_Arts_Living",
    "Do_It_Yourself_Lifestyle_Committed_Choice",
    "Highbrow_Living",
    "Professional_Living",
    "Home_Living",
    "Sporty_Living",
    "Upscale_Living",
    "Broader_Living",
    "Disabled_In_HH",
    "Lifestyle_Passion_Collectibles",
    "Movie_Collector",
    "Games_PC_Games",
    "Arts_Int",
    "Home_And_Garden",
    "Photography_Video_Equip",
    "Home_Furnishings_Decor",
    "Home_Improvement",
    "Sports_Leisure",
    "Luggage_Buyer",
    "Mail_Order_Buyer",
    "Mail_Responder",
    "Male_Merch_Buyer",
    "History_Military",
    "Electronics_Movies_Int",
    "Music_Avid_Listener",
    "Music_Collector",
    "Musical_Instruments",
    "Music_Player_Device",
    "Online_Buyer",
    "Opportunity_Seekers",
    "Outdoor_Enthusiast",
    "Outdoor_Sports_Lover",
    "Parenting_Int",
    "Childrens_General",
    "Grandchildren_Int",
    "Pets_Multi",
    "Photography_Int",
    "Current_Affairs_Politics",
    "Reading_Sci_Fi",
    "Religious_Inspiration",
    "Religious_Mags",
    "Science_Space",
    "Sewing_Knitting_Needlework",
    "Smoking",
    "Sports_Auto_Motorcycle_Racing",
    "Sports_Baseball",
    "Sports_Basketball",
    "Boating_Sailing",
    "Camping_Hiking",
    "Fisher",
    "Sports_Football",
    "Sports_Grouping",
    "Outdoor_Grouping",
    "Sports_Hockey",
    "Hunter",
    "Active_Motorcycle",
    "Active_Nascar",
    "Scuba_Diving",
    "Hunting_Shooting",
    "Active_Snow_Skiing",
    "Sports_Soccer",
    "Active_Tennis",
    "Sports_TV_Sports",
    "Sweepstakes_Int",
    "Travel_Int",
    "Travel_Cruises",
    "Travel_Domestic",
    "Travel_Grouping",
    "Travel_Intl",
    "Value_Hunter",
    "Veteran_In_HH",
    "Games_Video",
    "Food_Wines",
    "Woodwork",
    "Donor_Animal_Welfare",
    "Donor_Arts_Cultural",
    "Donor_Charitable_Causes",
    "Donor_Childrens_Causes",
    "Donor_By_Mail",
    "Donor_Environmental",
    "Donor_Environmental_Issues",
    "General_Contributor",
    "Donor_Health_Institution",
    "Donor_International_Aid",
    "Donor_Political_Conservative",
    "Donor_Political_Liberal",
    "Donor_Misc_Charitable",
    "Donor_Community_Charity",
    "Religious_Contributor",
    "Donor_Veterans",
    "AccessabilityElevatorFlag",
    "AccessabilityHandicapFlag",
    "ArborPergolaFlag",
    "ArenaFlag",
    "BathHouseFlag",
    "BoatAccessFlag",
    "BoatHouseFlag",
    "BoatLiftFlag",
    "BreezewayFlag",
    "CabinFlag",
    "CentralVacuumFlag",
    "ContentIntercomFlag",
    "ContentOverheadDoorFlag",
    "ContentSaunaFlag",
    "ContentSoundSystemFlag",
    "ContentStormShutterFlag",
    "CourtyardFlag",
    "DeckFlag",
    "EscalatorFlag",
    "FeatureBalconyFlag",
    "GazeboFlag",
    "GolfCourseGreenFlag",
    "GraineryFlag",
    "GreenHouseFlag",
    "GuestHouseFlag",
    "KennelFlag",
    "LeanToFlag",
    "OutdoorKitchenFireplaceFlag",
    "ParkingRVParkingFlag",
    "PondFlag",
    "PoolHouseFlag",
    "PoultryHouseFlag",
    "QuonsetFlag",
    "RoomsAtticFlag",
    "RoomsBonusRoomFlag",
    "RoomsBreakfastNookFlag",
    "RoomsCellarFlag",
    "RoomsCellarWineFlag",
    "RoomsExerciseFlag",
    "RoomsGameFlag",
    "RoomsGreatFlag",
    "RoomsHobbyFlag",
    "RoomsLaundryFlag",
    "RoomsMediaFlag",
    "RoomsMudFlag",
    "RoomsOfficeFlag",
    "RoomsSafeRoomFlag",
    "RoomsSittingFlag",
    "RoomsStudyFlag",
    "RoomsSunroomFlag",
    "SecurityAlarmFlag",
    "SiloFlag",
    "SportsCourtFlag",
    "SprinklersFlag",
    "StableFlag",
    "StorageBuildingFlag",
    "TennisCourtFlag",
    "WaterFeatureFlag",
    "WetBarFlag",
    "HasEmail",
    "GunOwner",
    "LikelyRecentEmployment_Primary_Exec_Indicator",
    "LikelyRecentEmployment_Email_Available_Indicator",
    "LikelyRecentEmployment_Female_Owned_Indicator",
    "LikelyRecentEmployment_Minority_Owned_Indicator",
    "LikelyRecentEmployment_Home_Based_Business_Indicator",
    "LikelyRecentEmployment_Small_Business_Indicator",
    "LikelyRecentEmployment_Manufacturing_Indicator",
    "LikelyRecentEmployment_Public_Indicator",
    "LikelyRecentEmployment_Non_Profit_Indicator",
    "LikelyRecentEmployment_Domestic_Foreign_Owner_Indicator",
    "Veteran",
] -%}
{%- set boolean_flags = [
    "Do_Not_Call",
    "Home_Swimming_Pool",
    "Secondary_Address_Present",
    "Residential_Delivery_Indicator",
    "Presence_Of_Children_in_HH",
    "Home_Mortgage_Lender_Known",
] -%}
{%- set ints = [
    "Inferred_Age",
    "DOB_Yr",
    "DOB_Mon",
    "Length_Of_Residence_Code",
    "Number_Of_Persons_In_HH",
    "Household_Number_Lines_Of_Credit",
    "Investments_Est_Re_Properties_Owned",
    "Number_Of_Children_in_HH",
    "Number_Of_Adults_in_HH",
    "Density",
    "Home_Purchase_Month",
    "Home_Purchase_Day",
    "Home_Purchase_Year",
    "Home_Year_Built",
    "Home_Est_Current_Value_ConfidenceScore",
    "TaxYearAssessed",
    "BedroomsCount",
    "BuildingsCount",
    "FireplaceCount",
    "ParkingSpaceCount",
    "PlumbingFixturesCount",
    "RoomsCount",
    "UnitsCount",
    "Mortgage_Loan_To_Value_Ratio",
    "Number_Of_Sources",
    "Auto_Buy_Interest",
    "Social_Ranking_Index_by_Individual",
    "Social_Ranking_Index_by_Area",
    "Likely_Income_Ranking_by_Area",
    "Likely_Educational_Attainment_Ranking_by_Area",
    "LikelyRecentEmployment_Location_Employee_Count",
    "LikelyRecentEmployment_Corporate_Employee_Total",
    "LikelyRecentEmployment_Year_Established",
    "Auto_Year_1",
    "Auto_Year_2",
    "Auto_Year_3",
    "Motorcycle_Year_1",
] -%}
{%- set bigints = [
    "Property_Home_Square_Footage",
    "Property_Land_Square_Footage",
    "Home_Purchase_Price",
    "Home_Est_Current_Value",
    "TaxAssessedValueTotal",
    "TaxMarketValueTotal",
    "ParkingCarportArea",
    "ParkingGarageArea",
    "PatioArea",
    "RoomsBasementArea",
    "RoomsBasementAreaFinished",
    "RoomsBasementAreaUnfinished",
    "RoomsOfficeArea",
    "RoomsUtilityArea",
    "Home_Mortgage_Amount",
    "Most_Recent_2nd_Mortgage_Amount",
    "Estimated_Home_Equity",
    "LikelyRecentEmployment_Location_Sales_Total",
    "LikelyRecentEmployment_Square_Footage",
] -%}
{%- set strings = [
    "Landline_Area_Code",
    "Time_Zone",
    "Salutation",
    "Unit_Designator",
    "City_Name",
    "City_Name_Abbr",
    "State",
    "Zip_Code",
    "Zip4",
    "Carrier_Route",
    "DPV",
    "Census_Tract",
    "Census_Block",
    "Census_Block_Group",
    "Lat_Long_Geo_RC_Code",
    "County_Code",
    "County_Name",
    "District_Congressional",
    "District_State_Senate",
    "District_State_House",
    "District_Legislative",
    "MSA",
    "MSA_Code",
    "CBSA",
    "CBSA_Code",
    "CSA",
    "CSA_Code",
    "Gender",
    "Age_Code",
    "BirthDate_ConfidenceID",
    "Marital_Status",
    "Occupation_Group",
    "Occupation_of_Person",
    "Ethnic_Code",
    "Ethnic_Group",
    "Hispanic_Country_Code",
    "Assimilation_Codes",
    "Language_Code",
    "Religion_Code",
    "Education_of_Person",
    "Business_Owner",
    "Political_Ideology",
    "Dwelling_Type",
    "Homeowner_Probability_Model",
    "Home_Air_Conditioning",
    "Home_Heating_System",
    "Home_Sewer",
    "Home_Water",
    "CRA_Income_Classification_Code",
    "Estimated_Income_Code",
    "Household_Net_Worth",
    "Credit_Rating",
    "Credit_Range_Newcredit",
    "CC_New_Issue",
    "Inferred_HH_Rank",
    "Generations_In_HH",
    "Political_Contributor",
    "Home_Purchase_Price_Code",
    "Home_Est_Current_Value_Code",
    "Construction",
    "DrivewayMaterial",
    "Exterior1Code",
    "FenceCode",
    "FlooringMaterialPrimary",
    "Foundation",
    "InteriorStructure",
    "ParkingCarport",
    "ParkingGarage",
    "Pool",
    "PorchCode",
    "RoofConstruction",
    "RoofMaterial",
    "RoomsFamilyCode",
    "RoomsStormShelter",
    "RoomsUtilityCode",
    "ShedCode",
    "StoriesCount",
    "StructureStyle",
    "ViewDescription",
    "Home_Mortgage_Amount_Code",
    "Home_Mortgage_Type",
    "Home_Mortgage_Lender_Name_Standardized",
    "Home_Mortgage_Loan_Type",
    "Home_Transaction_Type",
    "Most_Recent_2nd_Mortgage_Loan_Type_Code",
    "Most_Recent_2nd_Mortgage_Interest_Rate_Type",
    "Most_Recent_2nd_Lender_Name_Standardized",
    "Area_Below_Poverty_Level_Families",
    "Area_Below_Poverty_Level_Percent_Unemployed",
    "Area_Health_Insurance_Coverage_No_Health_Insurance_Coverage",
    "Area_Percent_Unemployed",
    "Area_Commuting_to_Work_Car_Truck_Van_Drove_Alone",
    "Area_Commuting_to_Work_Car_Truck_Van_Carpooled",
    "Area_Commuting_to_Work_Public_Transit_Excluding_Taxi",
    "Area_Commuting_to_Work_Walked",
    "Area_Commuting_to_Work_Other_Means",
    "Area_Commuting_to_Work_Work_at_Home",
    "Area_Occupation_Management_Business_Science_and_Arts",
    "Area_Occupation_Natural_Resources_Construction_Maintenance",
    "Area_Occupation_Production_Transportation_Material_Moving",
    "Area_Occupation_Sales_Office",
    "Area_Occupation_Service",
    "Area_Industry_Agriculture_Forestry_Fishing_Hunting_Mining",
    "Area_Industry_Arts_Entertainment_Recreation_Accommodation_Food_Services",
    "Area_Industry_Construction",
    "Area_Industry_Educational_Services_Healthcare_Social_Assistance",
    "Area_Industry_Finance_Insurance_Real_Estate_Rental_Leasing",
    "Area_Industry_Information",
    "Area_Industry_Manufacturing",
    "Area_Industry_Other_Services_Except_Public_Administration",
    "Area_Industry_Professional_Scientific_Management_Administrative_Waste_Mgt",
    "Area_Industry_Public_Administration",
    "Area_Industry_Retail_Trade",
    "Area_Industry_Transportation_Warehousing_Utilities",
    "Area_Industry_Wholesale_Trade",
    "Area_Class_of_Worker_Private_Wages_Salary_Workers",
    "Area_Class_of_Worker_Government_Workers",
    "Area_Class_of_Worker_Self_Employed_Non_Incorporated_Business_Workers",
    "Area_Class_of_Worker_Unpaid_Family_Workers",
    "Area_Income_Benefits_HH_Less_Than_$10000",
    "Area_Income_Benefits_HH_$10000_$14999",
    "Area_Income_Benefits_HH_$15000_$24999",
    "Area_Income_Benefits_HH_$25000_$34999",
    "Area_Income_Benefits_HH_$35000_$49999",
    "Area_Income_Benefits_HH_$50000_$74999",
    "Area_Income_Benefits_HH_$75000_$99999",
    "Area_Income_Benefits_HH_$100000_$149999",
    "Area_Income_Benefits_HH_$150000_$199999",
    "Area_Income_Benefits_HH_$200000+",
    "Area_Income_Benefits_Earningsfromsalarywages",
    "Area_Income_Benefits_Earnings_From_Social_Security",
    "Area_Income_Benefits_Earnings_From_Retirement_Income",
    "Area_Income_Benefits_Earnings_From_Supplemental_Security_Income",
    "Area_Income_Benefits_Earnings_From_Cash_Public_Assistance_Income",
    "Area_Income_Benefits_Food_Stamps_SNAP_Benefits_Past_12_Months",
    "Area_Income_Benefits_Families_Less_Than_$10000",
    "Area_Income_Benefits_Families_$10000_$14999",
    "Area_Income_Benefits_Families_$15000_$24999",
    "Area_Income_Benefits_Families_$25000_$34999",
    "Area_Income_Benefits_Families_$35000_$49999",
    "Area_Income_Benefits_Families_$50000_$74999",
    "Area_Income_Benefits_Families_$75000_$99999",
    "Area_Income_Benefits_Families_$100000_$149999",
    "Area_Income_Benefits_Families_$150000_$199999",
    "Area_Income_Benefits_Families_$200000+",
    "Geocode_Full",
    "RUS_Code",
    "LikelyRecentEmployment_Standardized_Title",
    "LikelyRecentEmployment_Source_Title",
    "LikelyRecentEmployment_Executive_Department",
    "LikelyRecentEmployment_Executive_Level",
    "LikelyRecentEmployment_Physical_Address_City",
    "LikelyRecentEmployment_Physical_Address_State",
    "LikelyRecentEmployment_Physical_Address_Zip",
    "LikelyRecentEmployment_Mailing_Address_City",
    "LikelyRecentEmployment_Mailing_Address_State",
    "LikelyRecentEmployment_Mailing_Address_Zip",
    "LikelyRecentEmployment_Mailing_Address_Zip4",
    "LikelyRecentEmployment_Area_Code",
    "LikelyRecentEmployment_EIN",
    "LikelyRecentEmployment_Business_Status_Description",
    "LikelyRecentEmployment_Ticker_Symbol",
    "LikelyRecentEmployment_Stock_Exchange",
    "LikelyRecentEmployment_Location_Employee_Description",
    "LikelyRecentEmployment_Location_Sales_Description",
    "LikelyRecentEmployment_Corporate_Employee_Description",
    "LikelyRecentEmployment_Years_In_Business_Range",
    "LikelyRecentEmployment_Minority_Type",
    "LikelyRecentEmployment_Primary_SIC_Code",
    "LikelyRecentEmployment_Primary_SIC_Description",
    "LikelyRecentEmployment_Primary_SIC_2Digit_Code",
    "LikelyRecentEmployment_Primary_SIC_2Digit_Description",
    "LikelyRecentEmployment_Primary_SIC_4Digit_Code",
    "LikelyRecentEmployment_Primary_SIC_4Digit_Description",
    "Auto_Make_1",
    "Auto_Model_1",
    "Auto_Series_1",
    "Auto_BodyClass_1",
    "Auto_Trim_1",
    "Auto_VehicleType_1",
    "Transaction_Type_1",
    "Auto_Purchase_Type_1",
    "Auto_Lien_1",
    "Auto_Fuel_Type_1",
    "Auto_Manufacturer_1",
    "Auto_Make_2",
    "Auto_Model_2",
    "Auto_Series_2",
    "Auto_BodyClass_2",
    "Auto_Trim_2",
    "Auto_VehicleType_2",
    "Transaction_Type_2",
    "Auto_Purchase_Type_2",
    "Auto_Lien_2",
    "Auto_Fuel_Type_2",
    "Auto_Manufacturer_2",
    "Auto_Make_3",
    "Auto_Model_3",
    "Auto_Series_3",
    "Auto_BodyClass_3",
    "Auto_Trim_3",
    "Auto_VehicleType_3",
    "Transaction_Type_3",
    "Auto_Purchase_Type_3",
    "Auto_Lien_3",
    "Auto_Fuel_Type_3",
    "Auto_Manufacturer_3",
    "Motorcycle_Make_1",
    "Motorcycle_Model_1",
    "MAID1_DeviceType",
    "MAID2_DeviceType",
    "MAID3_DeviceType",
    "MAID4_DeviceType",
    "MAID5_DeviceType",
    "Previous_Zip_Code",
    "Previous_State",
    "Moved_InOut_State",
    "Range_of_Last_Move",
    "HHGenderID",
    "PreviousAddress_City",
    "PreviousAddress_State",
    "PreviousAddress_Zip_Code",
    "Radio_Market_Area",
    "Most_Recent_2nd_Mortgage_Transaction_Type",
    "Crimes_All_Rate",
    "Crimes_Property_Rate",
    "Crimes_Violent_Rate",
    "Landline_Phone_ConfidenceCode",
    "Cell_Phone_ConfidenceCode",
    "Military_Branch",
    "MMA_Zone",
] -%}
{#- yyyy-MM values land on the first of the month. -#}
{%- set dates = {
    "Home_Est_Current_Value_Date": "yyyy-MM-dd",
    "Purchase_Mortgage_Date": "yyyyMMdd",
    "Most_Recent_2nd_Mortgage_Date": "yyyyMMdd",
    "Date_of_Last_Move": "yyyyMMdd",
    "RecordDate": "MM/dd/yyyy",
    "Auto_Estimated_Purchase_Date_1": "yyyy-MM",
    "Auto_Estimated_Purchase_Date_2": "yyyy-MM",
    "Auto_Estimated_Purchase_Date_3": "yyyy-MM",
    "Motorcycle_Estimated_Purchase_Date_1": "yyyy-MM",
} -%}
{%- set decimals = {
    "BathCount": "decimal(5, 2)",
    "Home_Mortgage_Rate": "decimal(7, 4)",
    "Most_Recent_2nd_Mortgage_Interest_Rate": "decimal(7, 4)",
    "home_est_value_change_1_year": "decimal(9, 2)",
    "home_est_value_change_3_year": "decimal(9, 2)",
    "home_est_value_change_5_year": "decimal(9, 2)",
    "Crimes_All_RankingPercentile": "decimal(4, 1)",
    "Crimes_Violent_RankingPercentile": "decimal(4, 1)",
    "Crimes_Property_RankingPercentile": "decimal(4, 1)",
} -%}
{#- L2 stores these in hundreds of dollars. -#}
{%- set hundreds_of_dollars = [
    "Census_Median_Home_Value",
    "Census_Median_HH_Income",
] -%}
{#- Rooftop coordinates locate a home; 3 decimals is about 100 m. -#}
{%- set rounded_coordinates = ["Latitude", "Longitude"] -%}

{%- set source_relation = source("l2_commercial", "l2_commercial_20260912_mi") -%}
{%- set selected = [] -%}
{%- for column in adapter.get_columns_in_relation(source_relation) -%}
    {%- set name = column.name -%}
    {%- set value = "nullif(trim(`" ~ name ~ "`), '')" -%}
    {%- set alias = name | lower | replace("$", "") | replace("+", "_plus") -%}
    {%- if name in dropped or name.endswith("_RETIRED") -%}
    {%- elif name in hashed_ids -%}
        {%- do selected.append("sha2(" ~ value ~ ", 256) as " ~ alias ~ "_hash") -%}
    {%- elif name in rounded_coordinates -%}
        {%- do selected.append(
            "round(try_cast(" ~ value ~ " as double), 3) as " ~ alias
        ) -%}
    {%- elif name in y_flags -%}
        {#- L2 writes Y or leaves the field blank. -#}
        {%- do selected.append(
            "case when "
            ~ value
            ~ " = 'Y' then true when "
            ~ value
            ~ " is null then false end as "
            ~ alias
        ) -%}
    {%- elif name in boolean_flags -%}
        {%- do selected.append(cast_to_boolean(value) ~ " as " ~ alias) -%}
    {%- elif name in ints -%}
        {%- do selected.append("try_cast(" ~ value ~ " as int) as " ~ alias) -%}
    {%- elif name in bigints -%}
        {%- do selected.append("try_cast(" ~ value ~ " as bigint) as " ~ alias) -%}
    {%- elif name in hundreds_of_dollars -%}
        {%- do selected.append(
            "try_cast(" ~ value ~ " as bigint) * 100 as " ~ alias
        ) -%}
    {%- elif name in decimals -%}
        {%- do selected.append(
            "try_cast(" ~ value ~ " as " ~ decimals[name] ~ ") as " ~ alias
        ) -%}
    {%- elif name in dates -%}
        {%- do selected.append(
            "try_to_date(" ~ value ~ ", '" ~ dates[name] ~ "') as " ~ alias
        ) -%}
    {%- elif name in strings -%} {%- do selected.append(value ~ " as " ~ alias) -%}
    {%- else -%}
        {{
            exceptions.raise_compiler_error(
                "Unclassified L2 commercial column '"
                ~ name
                ~ "'. Add it to a treatment list before it can be exposed."
            )
        }}
    {%- endif -%}
{%- endfor -%}

{#- Full in prod; a sample elsewhere so dev and CI builds stay small. Pass
    --vars '{l2_commercial_row_limit: null}' for a full dev build. -#}
{%- set row_limit = var(
    "l2_commercial_row_limit", none if target.name == "prod" else 100000
) -%}

with
    source as (
        select *
        from {{ source_relation }}
        {% if row_limit is not none %} limit {{ row_limit }} {% endif %}
    )

select {{ selected | join(",\n    ") }}
from source
