select
    id,
    archived,
    createdat as created_at,
    updatedat as updated_at,
    contacts,
    companies,
    deals,
    tickets,
    properties_hs_timestamp as hs_timestamp,
    properties_hs_call_direction as hs_call_direction,
    properties_hs_call_status as hs_call_status,
    properties_hs_call_disposition as hs_call_disposition,
    properties_hs_call_duration as hs_call_duration,
    properties_hs_call_callee_object_id as hs_call_callee_object_id,
    properties_hs_call_callee_object_type as hs_call_callee_object_type,
    properties_hs_call_from_number as hs_call_from_number,
    properties_hs_call_to_number as hs_call_to_number,
    properties_hs_call_has_voicemail as hs_call_has_voicemail,
    properties_hs_call_recording_url as hs_call_recording_url,
    properties_hs_call_body as hs_call_body,
    properties_hs_call_title as hs_call_title,
    properties_hs_call_source as hs_call_source,
    properties_hs_activity_type as hs_activity_type,
    properties_hubspot_owner_id as hubspot_owner_id,
    _airbyte_extracted_at
from {{ source("airbyte_source", "hubspot_api_engagements_calls") }}
