"""GENERATED by `loader extract-serving-structure` — do not edit by hand.

Serving-cluster PK / indexes / FKs captured from pg_catalog. Regenerate to refresh."""

from loader.people_api.schema.index_specs import ForeignKey, IndexDef, PrimaryKey

PRIMARY_KEYS: list[PrimaryKey] = []

INDEXES: list[IndexDef] = []

FOREIGN_KEYS: list[ForeignKey] = []
