"""Render extracted serving-structure records into an importable, committed Python module.

GENERATED FILE WARNING is embedded so reviewers know `_serving_seed.py` is produced by
`loader extract-serving-structure`, not hand-edited."""

from __future__ import annotations

from loader.people_api.schema.index_specs import ForeignKey, IndexDef, PrimaryKey

_HEADER = '''\
"""GENERATED by `loader extract-serving-structure` — do not edit by hand.

Serving-cluster PK / indexes / FKs captured from pg_catalog. Regenerate to refresh."""

from loader.people_api.schema.index_specs import ForeignKey, IndexDef, PrimaryKey
'''


def render_seed_module(pks: list[PrimaryKey], idxs: list[IndexDef], fks: list[ForeignKey]) -> str:
    lines = [_HEADER, ""]
    lines.append("PRIMARY_KEYS: list[PrimaryKey] = [")
    for p in pks:
        lines.append(
            f"    PrimaryKey(table={p.table!r}, constraint={p.constraint!r}, columns={p.columns!r}),"
        )
    lines.append("]")
    lines.append("")
    lines.append("INDEXES: list[IndexDef] = [")
    for i in idxs:
        lines.append(
            f"    IndexDef(table={i.table!r}, name={i.name!r}, sql={i.sql!r}, "
            f"unique={i.unique!r}, columns={i.columns!r}, where={i.where!r}),"
        )
    lines.append("]")
    lines.append("")
    lines.append("FOREIGN_KEYS: list[ForeignKey] = [")
    for f in fks:
        lines.append(f"    ForeignKey(table={f.table!r}, constraint={f.constraint!r}, sql={f.sql!r}),")
    lines.append("]")
    lines.append("")
    return "\n".join(lines)
