-- Creates the two tables the L2-to-BallotReady matcher writes to. dbt reads
-- both only as sources (model_predictions in
-- dbt/project/models/staging/__sources.yaml) and must never create or
-- populate either one -- dbt does not create a table it never populates.
-- The matcher (a container, not dbt) is the only writer.
--
-- Run by hand, once, ONE STATEMENT AT A TIME: the Statement Execution API
-- rejects multiple ';'-separated statements in a single call, so this file
-- cannot be piped in whole. Paste each CREATE TABLE into a Databricks SQL
-- editor, or feed each separately to the repo's helper:
--   python .claude/skills/databricks-query/scripts/dbsql.py -f <one-statement>
-- Splitting this file on ';' does NOT work -- a COMMENT literal below contains
-- one. Split on the 'create table' boundary.
--
-- Both tables are empty on creation and stay that way until the matcher's
-- first run.

create table if not exists goodparty_data_catalog.model_predictions.llm_l2_br_match_runs (
    run_id string not null comment 'Matcher-generated run key; the FK every results row carries. Generated by the matcher itself, before any result row exists to insert, which is why it cannot be the identity column below.',
    sequence bigint not null generated always as identity (start with 1 increment by 1) comment 'Ordering key for "latest attempt wins" (never confidence or match_status). An explicit insert into an identity column is refused by Delta, which is the actual uniqueness guarantee -- a UNIQUE constraint would not enforce anything, since Unity Catalog constraints other than this identity behavior are informational only.',
    status string not null comment 'RUNNING, COMPLETE, or REVOKED. Only COMPLETE runs are ever read downstream. REVOKED exists so a rolled-back run cannot be mistaken for RUNNING.',
    started_at timestamp not null,
    completed_at timestamp comment 'Null until the run completes.',
    revoked_reason string comment 'Free-text note on why a run was revoked. Rollback is a human decision made days after the run completed; without a recorded reason a REVOKED run is an operational dead end.',
    constraint llm_l2_br_match_runs_pk primary key (sequence)
);

create table if not exists goodparty_data_catalog.model_predictions.llm_l2_br_match_results (
    run_id string not null comment 'FK to llm_l2_br_match_runs.run_id.',
    br_database_id int not null comment 'BallotReady office database id -- int, matching the type stg_airbyte_source__ballotready_api_position casts it to (cast(databaseid as int)).',
    l2_state string comment 'State of the matched district. Completes the district key to (state, type, name), which is the grain the universe, the district mart and the overrides seed all use -- without it a same-named district in another state resolves silently. Null on an ABSTAINED row.',
    l2_district_type string comment 'Null on an ABSTAINED row.',
    l2_district_name string comment 'Null on an ABSTAINED row.',
    match_status string not null comment 'MATCHED or ABSTAINED only. A technical error fails the run rather than being persisted as a match; there is no error state here.',
    confidence bigint comment 'Match confidence. Same type as the frozen January snapshot (model_predictions.llm_l2_br_match_20260126.confidence): an integer score, observed 0-100, not a 0-1 float.',
    attempted_at timestamp not null comment 'When the attempt was made -- the 30-day pending clock. The baseline run stamps this with the January date the office was actually matched, not the day it was loaded into this table.'
);
