{{ config(materialized="view") }}

with
    source as (

        select * from {{ source("airbyte_source", "ballotready_s3_uscities_v1_77") }}

    ),

    renamed as (

        select
            _airbyte_raw_id,
            _airbyte_extracted_at,
            _airbyte_meta,
            _airbyte_generation_id,
            cast(id as int) as id,
            cast(ccdp as boolean) as ccdp,
            cast(lat as float) as lat,
            cast(lng as float) as lng,
            city,
            cast(male as float) as male,
            zips,
            cast(female as float) as female,
            source,
            cast(age_20s as float) as age_20s,
            cast(age_30s as float) as age_30s,
            cast(age_40s as float) as age_40s,
            cast(age_50s as float) as age_50s,
            cast(age_60s as float) as age_60s,
            cast(age_70s as float) as age_70s,
            cast(density as float) as density,
            cast(married as float) as married,
            cast(poverty as float) as poverty,
            cast(ranking as float) as ranking,
            cast(veteran as float) as veteran,
            cast(widowed as float) as widowed,
            city_alt,
            cast(ccsa_fips as int) as ccsa_fips,
            csa_name,
            cast(disabled as float) as disabled,
            cast(divorced as float) as divorced,
            cast(hispanic as float) as hispanic,
            cast(military as boolean) as military,
            state_id,
            timezone,
            cast(township as boolean) as township,
            cast(cbsa_fips as int) as cbsa_fips,
            cbsa_name,
            cast(age_median as float) as age_median,
            cast(cbsa_metro as boolean) as cbsa_metro,
            city_ascii,
            cast(home_value as float) as home_value,
            cast(population as int) as population,
            cast(race_asian as float) as race_asian,
            cast(race_black as float) as race_black,
            cast(race_other as float) as race_other,
            cast(race_white as float) as race_white,
            state_name,
            cast(age_over_18 as float) as age_over_18,
            cast(age_over_65 as float) as age_over_65,
            cast(age_over_80 as float) as age_over_80,
            cast(county_fips as int) as county_fips,
            county_name,
            cast(family_size as float) as family_size,
            cast(race_native as float) as race_native,
            cast(rent_burden as float) as rent_burden,
            cast(rent_median as float) as rent_median,
            cast(age_10_to_19 as float) as age_10_to_19,
            cast(age_18_to_24 as float) as age_18_to_24,
            cast(age_under_10 as float) as age_under_10,
            cast(commute_time as float) as commute_time,
            cast(incorporated as boolean) as incorporated,
            cast(race_pacific as float) as race_pacific,
            cast(housing_units as int) as housing_units,
            cast(never_married as float) as never_married,
            cast(race_multiple as float) as race_multiple,
            cast(home_ownership as float) as home_ownership,
            county_fips_all,
            county_name_all,
            cast(limited_english as float) as limited_english,
            cast(health_uninsured as float) as health_uninsured,
            cast(population_proper as int) as population_proper,
            cast(unemployment_rate as float) as unemployment_rate,
            cast(education_graduate as float) as education_graduate,
            cast(family_dual_income as float) as family_dual_income,
            _ab_source_file_url,
            cast(education_bachelors as float) as education_bachelors,
            cast(education_highschool as float) as education_highschool,
            cast(education_stem_degree as float) as education_stem_degree,
            cast(education_some_college as float) as education_some_college,
            cast(income_household_median as float) as income_household_median,
            cast(income_household_5_to_10 as float) as income_household_5_to_10,
            cast(income_household_under_5 as float) as income_household_under_5,
            cast(income_individual_median as float) as income_individual_median,
            cast(education_less_highschool as float) as education_less_highschool,
            cast(income_household_10_to_15 as float) as income_household_10_to_15,
            cast(income_household_150_over as float) as income_household_150_over,
            cast(income_household_15_to_20 as float) as income_household_15_to_20,
            cast(income_household_20_to_25 as float) as income_household_20_to_25,
            cast(income_household_25_to_35 as float) as income_household_25_to_35,
            cast(income_household_35_to_50 as float) as income_household_35_to_50,
            cast(income_household_50_to_75 as float) as income_household_50_to_75,
            cast(labor_force_participation as float) as labor_force_participation,
            cast(education_college_or_above as float) as education_college_or_above,
            cast(income_household_75_to_100 as float) as income_household_75_to_100,
            cast(income_household_100_to_150 as float) as income_household_100_to_150,
            cast(income_household_six_figure as float) as income_household_six_figure,
            _ab_source_file_last_modified

        from source

    )

select *
from renamed
