with
    source as (
        select * from {{ source("airbyte_source", "techspeed_gdrive_candidates") }}
    ),
    renamed as (
        select
            {{ adapter.quote("_airbyte_raw_id") }},
            {{ adapter.quote("_airbyte_extracted_at") }},
            {{ adapter.quote("_airbyte_meta") }},
            {{ adapter.quote("_airbyte_generation_id") }},
            {{ adapter.quote("city") }},
            {{ adapter.quote("email") }},
            {{ adapter.quote("party") }},
            {{ adapter.quote("phone") }},
            {{ adapter.quote("state") }},
            {{ adapter.quote("partisan") }},
            {{ adapter.quote("last_name") }},
            {{ adapter.quote("open_seat") }},
            {{ adapter.quote("ts_status") }},
            {{ adapter.quote("first_name") }},
            {{ adapter.quote("is_primary") }},
            {{ adapter.quote("is_veteran") }},
            {{ adapter.quote("population") }},
            {{ adapter.quote("source_url") }},
            {{ adapter.quote("ts_comment") }},
            {{ adapter.quote("office_name") }},
            {{ adapter.quote("office_type") }},
            {{ adapter.quote("phone_clean") }},
            {{ adapter.quote("postal_code") }},
            {{ adapter.quote("website_url") }},
            {{ adapter.quote("email_source") }},
            {{ adapter.quote("facebook_url") }},
            {{ adapter.quote("is_incumbent") }},
            {{ adapter.quote("linkedin_url") }},
            {{ adapter.quote("office_level") }},
            {{ adapter.quote("phone_source") }},
            {{ adapter.quote("district_name") }},
            {{ adapter.quote("date_processed") }},
            {{ adapter.quote("is_uncontested") }},
            {{ adapter.quote("street_address") }},
            {{ adapter.quote("twitter_handle") }},
            {{ adapter.quote("election_result") }},
            {{ adapter.quote("filing_deadline") }},
            {{ adapter.quote("seats_available") }},
            {{ adapter.quote("instagram_handle") }},
            {{ adapter.quote("candidate_id_tier") }},
            {{ adapter.quote("number_candidates") }},
            {{ adapter.quote("office_normalized") }},
            {{ adapter.quote("_ab_source_file_url") }},
            {{ adapter.quote("ballotready_race_id") }},
            {{ adapter.quote("candidate_id_source") }},
            {{ adapter.quote("county_municipality") }},
            {{ adapter.quote("normalized_location") }},
            {{ adapter.quote("phone_type_select_1") }},
            {{ adapter.quote("general_election_date") }},
            {{ adapter.quote("primary_election_date") }},
            {{ adapter.quote("ts_found_race_net_new") }},
            {{ adapter.quote("date_of_birth_mmddyyyy") }},
            {{ adapter.quote("ts_found_candidate_net_new") }},
            {{ adapter.quote("_ab_source_file_last_modified") }}

        from source
    )
select *
from renamed
