"""Step 0 — inspect the current Present cluster for the validate baseline (DATA-1907).

Captures, per prod table (Voter + the District family), total and per-state row counts
plus L2 snapshot freshness (max(updated_at) per state). Voter's per-state counts are the
"old" baseline the validate step diffs the freshly loaded cluster against.

The schema is generated by `emit-ddl` (target_schema.sql) + `extract-serving-structure`
(the _serving_seed), not here; this step also logs a best-effort warning if the live Voter
indexes diverge from that committed seed. Per-state counts are captured only for tables that
actually have a "State" column (detected at runtime), so a District table without one yields
a total count rather than erroring.

The CLI writes the manifest to s3://.../voter_export_{date}/_manifest/inspect.json; the
Airflow xcom the validate step reads is the DAG's concern (the manifest is the contract).
"""

from __future__ import annotations

from datetime import UTC, datetime

import psycopg

from loader.core.log import bind, get_logger
from loader.people_api.config import LoaderConfig
from loader.people_api.db import connect_prod
from loader.people_api.manifests import (
    InspectManifest,
    TableInspection,
    manifest_uri,
    read_manifest,
    write_manifest,
)
from loader.people_api.schema import schema_spec
from loader.people_api.schema.serving_structure import extract_indexes

log = get_logger(__name__)

# Voter is required; the District family is best-effort (may be absent on a cluster).
_REQUIRED_TABLE = "Voter"
_OPTIONAL_TABLES: tuple[str, ...] = ("DistrictVoter", "District", "DistrictStats")


def _has_column(cur: psycopg.Cursor, table: str, column: str) -> bool:
    cur.execute(
        "SELECT 1 FROM information_schema.columns "
        "WHERE table_schema='public' AND table_name=%s AND column_name=%s",
        (table, column),
    )
    return cur.fetchone() is not None


def _scalar_int(cur: psycopg.Cursor) -> int:
    row = cur.fetchone()
    return int(row[0]) if row and row[0] is not None else 0


def _index_drift(live: set[str], seeded: set[str]) -> tuple[list[str], list[str]]:
    """(indexes only on the live cluster, indexes only in the committed seed)."""
    return sorted(live - seeded), sorted(seeded - live)


def _inspect_table(cur: psycopg.Cursor, table: str) -> TableInspection:
    """Inspect one table in a single scan where possible.

    When the table has a "State" column, one GROUP BY scan yields the per-state counts, the
    per-state snapshot freshness (max(updated_at), when that column exists), AND the total row
    count — summed over every group, *including* a NULL-State group, so the total still equals the
    full-table count. This avoids a separate count(*) scan (these tables are large; each extra
    full scan is expensive). A table without a "State" column falls back to a plain count(*).
    """
    # Table names are from a fixed constant tuple (not user input); f-strings are safe here.
    if not _has_column(cur, table, "State"):
        cur.execute(f'SELECT count(*) FROM public."{table}"')  # ty: ignore[no-matching-overload]
        return TableInspection(table=table, total_row_count=_scalar_int(cur))

    has_updated = _has_column(cur, table, "updated_at")
    cols = "count(*), max(updated_at)" if has_updated else "count(*)"
    cur.execute(f'SELECT "State", {cols} FROM public."{table}" GROUP BY "State"')  # ty: ignore[no-matching-overload]

    total = 0
    per_state: dict[str, int] = {}
    snapshot: dict[str, str] = {}
    for r in cur.fetchall():
        state, count = r[0], int(r[1])
        total += count  # includes the NULL-State group, so total == full-table count
        if state is None:
            continue
        per_state[state] = count
        if has_updated and r[2] is not None:
            snapshot[state] = r[2].isoformat()
    return TableInspection(
        table=table,
        total_row_count=total,
        per_state_row_counts=per_state,
        per_state_snapshot_dates=snapshot,
    )


def run(cfg: LoaderConfig, run_date: str) -> InspectManifest:
    bind(run_date=run_date, step="inspect")
    existing = read_manifest(cfg, run_date, "inspect", InspectManifest)
    if existing and existing.status == "complete":
        log.info(
            "inspect.skip", reason="manifest already complete", uri=manifest_uri(cfg, run_date, "inspect")
        )
        return existing

    started = datetime.now(UTC)
    log.info("inspect.start", prod_cluster_id=cfg.prod_cluster_id)

    tables: list[TableInspection] = []
    with connect_prod(cfg) as conn, conn.cursor() as cur:
        # Voter is required — let a failure propagate so we never write a partial
        # "complete" manifest missing the baseline validate depends on.
        # This scan is the step's dominant cost (full-table aggregate over the largest table);
        # log before it so the run shows progress rather than going silent mid-scan.
        log.info("inspect.table_scan_start", table=_REQUIRED_TABLE)
        voter = _inspect_table(cur, _REQUIRED_TABLE)
        tables.append(voter)
        log.info(
            "inspect.table",
            table=_REQUIRED_TABLE,
            total=voter.total_row_count,
            states=len(voter.per_state_row_counts),
        )
        # No per-state baseline = no usable validate input. Fail before writing a
        # "complete" manifest, else inspect's skip-guard + validate's missing-baseline
        # failure wedge the pipeline (both need a manual S3 delete to recover).
        if not voter.per_state_row_counts:
            raise RuntimeError(
                f"Voter has no per-state row counts (total={voter.total_row_count}); inspect "
                'cannot produce a validate baseline — check the "State" column exists on the '
                "prod cluster and the table is non-empty."
            )
        # The District family is best-effort: a table absent on this cluster is skipped,
        # not fatal. connect_prod is autocommit, so a failed query doesn't poison the rest.
        for table in _OPTIONAL_TABLES:
            try:
                log.info("inspect.table_scan_start", table=table)
                ti = _inspect_table(cur, table)
                tables.append(ti)
                log.info("inspect.table", table=table, total=ti.total_row_count)
            except psycopg.errors.UndefinedTable as e:
                # Relation-not-found (SQLSTATE 42P01): this cluster lacks the optional table.
                # Anything else — including a transient OperationalError (connection drop) —
                # propagates, so we never write a silently-incomplete "complete" manifest.
                log.warning("inspect.table_skip", table=table, error=str(e))

        # Advisory: flag if the live Voter indexes diverge from the committed seed (e.g. the
        # seed was captured from a different cluster, or prod changed out-of-band). Best-effort
        # — a drift-check hiccup must never fail inspect, which produces the validate baseline.
        try:
            live = {i.name for i in extract_indexes(cur, [_REQUIRED_TABLE])}
            only_live, only_seed = _index_drift(
                live, {i.name for i in schema_spec.indexes_for(_REQUIRED_TABLE)}
            )
            if only_live or only_seed:
                log.warning(
                    "inspect.index_drift", table=_REQUIRED_TABLE, only_live=only_live, only_seed=only_seed
                )
        except Exception as e:  # advisory check, never fatal
            log.warning("inspect.index_drift_check_failed", error=str(e))

    manifest = InspectManifest(
        run_date=run_date,
        status="complete",
        started_at=started,
        finished_at=datetime.now(UTC),
        prod_cluster_id=cfg.prod_cluster_id,
        tables=tables,
    )
    uri = write_manifest(cfg, manifest)
    log.info("inspect.complete", uri=uri, tables=len(tables))
    return manifest
