with
    source_voters as (select * from {{ ref("m_people_api__voter") }}),

    deid_voters as (
        select
            -- Core identifiers
            id,
            lalvoterid,
            state,

            -- Household identifiers (hashed from address components)
            sha2(
                concat_ws(
                    '|',
                    coalesce(mailing_addresses_housenumber, ''),
                    coalesce(mailing_addresses_addressline, ''),
                    coalesce(mailing_addresses_extraaddressline, ''),
                    coalesce(mailing_addresses_apartmentnum, ''),
                    coalesce(mailing_addresses_apartmenttype, ''),
                    coalesce(mailing_addresses_city, ''),
                    coalesce(mailing_addresses_state, ''),
                    coalesce(cast(mailing_addresses_zip as string), '')
                ),
                256
            ) as mailing_household_hash,
            sha2(
                concat_ws(
                    '|',
                    coalesce(residence_addresses_housenumber, ''),
                    coalesce(residence_addresses_addressline, ''),
                    coalesce(residence_addresses_extraaddressline, ''),
                    coalesce(residence_addresses_apartmentnum, ''),
                    coalesce(residence_addresses_apartmenttype, ''),
                    coalesce(residence_addresses_city, ''),
                    coalesce(residence_addresses_state, ''),
                    coalesce(nullif(residence_addresses_zip, ''), '')
                ),
                256
            ) as residence_household_hash,
            mailing_families_familyid,

            -- Demographics (non-identifying)
            absenteetypes_description,
            active,
            age_int,
            gender,
            business_owner,
            calculatedregdate,
            countyethnic_description,
            countyethnic_lalethniccode,
            education_of_person,
            estimated_income_amount_int,
            ethnicgroups_ethnicgroup1desc,
            ethnic_description,
            homeowner_probability_model,
            language_code,
            marital_status,
            movedfrom_date,
            movedfrom_party_description,
            movedfrom_state,
            officialregdate,
            parties_description,
            placeofbirth,
            presence_of_children,
            veteran_status,
            voterparties_change_changed_party,
            voter_status,
            voter_status_updatedat,

            mailing_addresses_city,
            mailing_addresses_state,
            cast(mailing_addresses_zip as string) as mailing_addresses_zip,

            residence_addresses_city,
            residence_addresses_latlongaccuracy,
            -- Round lat/long to 3 decimal places (~100m precision) for privacy
            round(residence_addresses_latitude, 3) as residence_addresses_latitude,
            round(residence_addresses_longitude, 3) as residence_addresses_longitude,
            residence_addresses_state,
            nullif(residence_addresses_zip, '') as residence_addresses_zip,
            residence_hhparties_description,

            -- Voter turnout (all boolean flags)
            anyelection_2017,
            anyelection_2019,
            anyelection_2021,
            anyelection_2023,
            anyelection_2025,
            general_2016,
            general_2018,
            general_2020,
            general_2022,
            general_2024,
            general_2026,
            otherelection_2016,
            otherelection_2018,
            otherelection_2020,
            otherelection_2022,
            otherelection_2024,
            otherelection_2026,
            presidentialprimary_2016,
            presidentialprimary_2020,
            presidentialprimary_2024,
            primary_2016,
            primary_2018,
            primary_2020,
            primary_2022,
            primary_2024,
            primary_2026,
            votingperformanceevenyeargeneral,
            votingperformanceevenyeargeneralandprimary,
            votingperformanceevenyearprimary,
            votingperformanceminorelection,

            -- All district fields (retained for analysis)
            addressdistricts_change_changed_cd,
            addressdistricts_change_changed_county,
            addressdistricts_change_changed_hd,
            addressdistricts_change_changed_ld,
            addressdistricts_change_changed_sd,
            airport_district,
            annexation_district,
            aquatic_center_district,
            aquatic_district,
            assessment_district,
            bay_area_rapid_transit,
            board_of_education_district,
            board_of_education_subdistrict,
            bonds_district,
            borough,
            borough_ward,
            career_center,
            cemetery_district,
            central_committee_district,
            chemical_control_district,
            committee_super_district,
            city,
            city_council_commissioner_district,
            city_mayoral_district,
            city_school_district,
            city_ward,
            coast_water_district,
            college_board_district,
            communications_district,
            community_college_at_large,
            community_college_commissioner_district,
            community_college_subdistrict,
            community_council_district,
            community_council_subdistrict,
            community_facilities_district,
            community_facilities_subdistrict,
            community_hospital_district,
            community_planning_area,
            community_service_district,
            community_service_subdistrict,
            congressional_township,
            conservation_district,
            conservation_subdistrict,
            consolidated_water_district,
            control_zone_district,
            corrections_district,
            county,
            county_board_of_education_district,
            county_board_of_education_subdistrict,
            county_community_college_district,
            county_commissioner_district,
            county_fire_district,
            county_hospital_district,
            county_legislative_district,
            county_library_district,
            county_memorial_district,
            county_paramedic_district,
            county_service_area,
            county_service_area_subdistrict,
            county_sewer_district,
            county_superintendent_of_schools_district,
            county_supervisorial_district,
            county_unified_school_district,
            county_water_district,
            county_water_landowner_district,
            county_water_subdistrict,
            democratic_convention_member,
            democratic_zone,
            designated_market_area_dma,
            district_attorney,
            drainage_district,
            education_commission_district,
            educational_service_district,
            educational_service_subdistrict,
            election_commissioner_district,
            elementary_school_district,
            elementary_school_subdistrict,
            emergency_communication_911_district,
            emergency_communication_911_subdistrict,
            enterprise_zone_district,
            ext_district,
            exempted_village_school_district,
            facilities_improvement_district,
            fips,
            fire_district,
            fire_maintenance_district,
            fire_protection_district,
            fire_protection_subdistrict,
            fire_protection_tax_measure_district,
            fire_service_area_district,
            fire_subdistrict,
            flood_control_zone,
            forest_preserve,
            garbage_district,
            geological_hazard_abatement_district,
            hamlet_community_area,
            health_district,
            high_school_district,
            high_school_subdistrict,
            hospital_subdistrict,
            improvement_landowner_district,
            independent_fire_district,
            irrigation_district,
            irrigation_subdistrict,
            island,
            judicial_appellate_district,
            judicial_circuit_court_district,
            judicial_county_board_of_review_district,
            judicial_county_court_district,
            judicial_district,
            judicial_district_court_district,
            judicial_family_court_district,
            judicial_jury_district,
            judicial_juvenile_court_district,
            judicial_magistrate_division,
            judicial_municipal_court_district,
            judicial_sub_circuit_district,
            judicial_superior_court_district,
            judicial_supreme_court_district,
            landscaping_and_lighting_assessment_district,
            land_commission,
            law_enforcement_district,
            learning_community_coordinating_council_district,
            levee_district,
            levee_reconstruction_assesment_district,
            library_district,
            library_services_district,
            library_subdistrict,
            lighting_district,
            local_hospital_district,
            local_park_district,
            maintenance_district,
            master_plan_district,
            memorial_district,
            metro_service_district,
            metro_service_subdistrict,
            metro_transit_district,
            metropolitan_water_district,
            middle_school_district,
            mosquito_abatement_district,
            mountain_water_district,
            multi_township_assessor,
            municipal_advisory_council_district,
            municipal_utility_district,
            municipal_utility_subdistrict,
            municipal_water_district,
            municipal_water_subdistrict,
            museum_district,
            northeast_soil_and_water_district,
            open_space_district,
            open_space_subdistrict,
            other,
            paramedic_district,
            park_commissioner_district,
            park_district,
            park_subdistrict,
            planning_area_district,
            police_district,
            port_district,
            port_subdistrict,
            power_district,
            precinct,
            proposed_city,
            proposed_city_commissioner_district,
            proposed_community_college,
            proposed_district,
            proposed_elementary_school_district,
            proposed_fire_district,
            proposed_unified_school_district,
            public_airport_district,
            public_regulation_commission,
            public_service_commission_district,
            public_utility_district,
            public_utility_subdistrict,
            rapid_transit_district,
            rapid_transit_subdistrict,
            reclamation_district,
            recreation_district,
            recreational_subdistrict,
            regional_office_of_education_district,
            republican_area,
            republican_convention_member,
            resort_improvement_district,
            resource_conservation_district,
            river_water_district,
            road_maintenance_district,
            rural_service_district,
            sanitary_district,
            sanitary_subdistrict,
            school_board_district,
            school_district,
            school_district_vocational,
            school_facilities_improvement_district,
            school_subdistrict,
            service_area_district,
            sewer_district,
            sewer_maintenance_district,
            sewer_subdistrict,
            snow_removal_district,
            special_reporting_district,
            special_tax_district,
            state_house_district,
            state_legislative_district,
            state_senate_district,
            storm_water_district,
            street_lighting_district,
            superintendent_of_schools_district,
            tv_translator_district,
            town_council,
            town_district,
            town_ward,
            township,
            township_ward,
            transit_district,
            transit_subdistrict,
            tricity_service_district,
            us_congressional_district,
            unified_school_district,
            unified_school_subdistrict,
            unincorporated_district,
            unincorporated_park_district,
            unprotected_fire_district,
            ute_creek_soil_district,
            vector_control_district,
            village,
            village_ward,
            vote_by_mail_area,
            wastewater_district,
            water_agency,
            water_agency_subdistrict,
            water_conservation_district,
            water_conservation_subdistrict,
            water_control_water_conservation,
            water_control_water_conservation_subdistrict,
            water_district,
            water_public_utility_district,
            water_public_utility_subdistrict,
            water_replacement_district,
            water_replacement_subdistrict,
            water_subdistrict,
            weed_district,

            -- Timestamps
            created_at,
            updated_at

        from source_voters
    )

select *
from deid_voters
