/*
De-identified voter data for Analytics program (MBAN 2026).

This model provides nationwide voter data with PII removed or hashed to protect individual privacy
while maintaining analytical utility for educational purposes.

De-identification approach:
- Names removed entirely (cannot be reverse-engineered via hash lookups)
- Phone numbers and email addresses removed
- Phone confidence scores removed (CellConfidenceCode, LandlineConfidenceCode)
- Address lines hashed into household identifiers (mailing_household_hash, residence_household_hash)
- Voter ID (LALVOTERID) retained for record linkage
- Geographic aggregates (city, state, zip only) retained - detailed address components removed
- Coordinates rounded to 3 decimal places (~100m precision) for privacy
- String versions of numeric fields removed (Age, Estimated_Income_Amount) to retain only integer versions
- Sequence/ordering fields removed (SequenceOddEven, SequenceZigZag) to prevent household ordering inference
*/
with
    source_voters as (select * from {{ ref("m_people_api__voter") }}),

    deid_voters as (
        select
            -- Core identifiers (retained)
            id,
            `LALVOTERID`,
            `State`,

            -- Household identifiers (hashed from address components)
            sha2(
                concat_ws(
                    '|',
                    coalesce(`Mailing_Addresses_HouseNumber`, ''),
                    coalesce(`Mailing_Addresses_AddressLine`, ''),
                    coalesce(`Mailing_Addresses_ExtraAddressLine`, ''),
                    coalesce(`Mailing_Addresses_ApartmentNum`, ''),
                    coalesce(`Mailing_Addresses_ApartmentType`, ''),
                    coalesce(`Mailing_Addresses_City`, ''),
                    coalesce(`Mailing_Addresses_State`, ''),
                    coalesce(cast(`Mailing_Addresses_Zip` as string), '')
                ),
                256
            ) as mailing_household_hash,
            sha2(
                concat_ws(
                    '|',
                    coalesce(`Residence_Addresses_HouseNumber`, ''),
                    coalesce(`Residence_Addresses_AddressLine`, ''),
                    coalesce(`Residence_Addresses_ExtraAddressLine`, ''),
                    coalesce(`Residence_Addresses_ApartmentNum`, ''),
                    coalesce(`Residence_Addresses_ApartmentType`, ''),
                    coalesce(`Residence_Addresses_City`, ''),
                    coalesce(`Residence_Addresses_State`, ''),
                    coalesce(nullif(`Residence_Addresses_Zip`, ''), '')
                ),
                256
            ) as residence_household_hash,
            `Mailing_Families_FamilyID`,

            -- Demographics (non-identifying)
            `AbsenteeTypes_Description`,
            `Active`,
            `Age_Int`,
            `Gender`,
            `Business_Owner`,
            `CalculatedRegDate`,
            `CountyEthnic_Description`,
            `CountyEthnic_LALEthnicCode`,
            `Education_Of_Person`,
            `Estimated_Income_Amount_Int`,
            `EthnicGroups_EthnicGroup1Desc`,
            `Ethnic_Description`,
            `Homeowner_Probability_Model`,
            `Language_Code`,
            `Marital_Status`,
            `MovedFrom_Date`,
            `MovedFrom_Party_Description`,
            `MovedFrom_State`,
            `OfficialRegDate`,
            `Parties_Description`,
            `PlaceOfBirth`,
            `Presence_Of_Children`,
            `Veteran_Status`,
            `VoterParties_Change_Changed_Party`,
            `Voter_Status`,
            `Voter_Status_UpdatedAt`,

            `Mailing_Addresses_City`,
            `Mailing_Addresses_State`,
            cast(`Mailing_Addresses_Zip` as string) as `Mailing_Addresses_Zip`,

            `Residence_Addresses_City`,
            `Residence_Addresses_LatLongAccuracy`,
            -- Round lat/long to 3 decimal places (~100m precision) for privacy
            round(`Residence_Addresses_Latitude`, 3) as `Residence_Addresses_Latitude`,
            round(
                `Residence_Addresses_Longitude`, 3
            ) as `Residence_Addresses_Longitude`,
            `Residence_Addresses_State`,
            nullif(`Residence_Addresses_Zip`, '') as `Residence_Addresses_Zip`,
            `Residence_HHParties_Description`,

            -- Voter turnout (all boolean flags)
            `AnyElection_2017`,
            `AnyElection_2019`,
            `AnyElection_2021`,
            `AnyElection_2023`,
            `AnyElection_2025`,
            `General_2016`,
            `General_2018`,
            `General_2020`,
            `General_2022`,
            `General_2024`,
            `General_2026`,
            `OtherElection_2016`,
            `OtherElection_2018`,
            `OtherElection_2020`,
            `OtherElection_2022`,
            `OtherElection_2024`,
            `OtherElection_2026`,
            `PresidentialPrimary_2016`,
            `PresidentialPrimary_2020`,
            `PresidentialPrimary_2024`,
            `Primary_2016`,
            `Primary_2018`,
            `Primary_2020`,
            `Primary_2022`,
            `Primary_2024`,
            `Primary_2026`,
            `VotingPerformanceEvenYearGeneral`,
            `VotingPerformanceEvenYearGeneralAndPrimary`,
            `VotingPerformanceEvenYearPrimary`,
            `VotingPerformanceMinorElection`,

            -- All district fields (retained for analysis)
            `AddressDistricts_Change_Changed_CD`,
            `AddressDistricts_Change_Changed_County`,
            `AddressDistricts_Change_Changed_HD`,
            `AddressDistricts_Change_Changed_LD`,
            `AddressDistricts_Change_Changed_SD`,
            `Airport_District`,
            `Annexation_District`,
            `Aquatic_Center_District`,
            `Aquatic_District`,
            `Assessment_District`,
            `Bay_Area_Rapid_Transit`,
            `Board_of_Education_District`,
            `Board_of_Education_SubDistrict`,
            `Bonds_District`,
            `Borough`,
            `Borough_Ward`,
            `Career_Center`,
            `Cemetery_District`,
            `Central_Committee_District`,
            `Chemical_Control_District`,
            `Committee_Super_District`,
            `City`,
            `City_Council_Commissioner_District`,
            `City_Mayoral_District`,
            `City_School_District`,
            `City_Ward`,
            `Coast_Water_District`,
            `College_Board_District`,
            `Communications_District`,
            `Community_College_At_Large`,
            `Community_College_Commissioner_District`,
            `Community_College_SubDistrict`,
            `Community_Council_District`,
            `Community_Council_SubDistrict`,
            `Community_Facilities_District`,
            `Community_Facilities_SubDistrict`,
            `Community_Hospital_District`,
            `Community_Planning_Area`,
            `Community_Service_District`,
            `Community_Service_SubDistrict`,
            `Congressional_Township`,
            `Conservation_District`,
            `Conservation_SubDistrict`,
            `Consolidated_Water_District`,
            `Control_Zone_District`,
            `Corrections_District`,
            `County`,
            `County_Board_of_Education_District`,
            `County_Board_of_Education_SubDistrict`,
            `County_Community_College_District`,
            `County_Commissioner_District`,
            `County_Fire_District`,
            `County_Hospital_District`,
            `County_Legislative_District`,
            `County_Library_District`,
            `County_Memorial_District`,
            `County_Paramedic_District`,
            `County_Service_Area`,
            `County_Service_Area_SubDistrict`,
            `County_Sewer_District`,
            `County_Superintendent_of_Schools_District`,
            `County_Supervisorial_District`,
            `County_Unified_School_District`,
            `County_Water_District`,
            `County_Water_Landowner_District`,
            `County_Water_SubDistrict`,
            `Democratic_Convention_Member`,
            `Democratic_Zone`,
            `Designated_Market_Area_DMA`,
            `District_Attorney`,
            `Drainage_District`,
            `Education_Commission_District`,
            `Educational_Service_District`,
            `Educational_Service_Subdistrict`,
            `Election_Commissioner_District`,
            `Elementary_School_District`,
            `Elementary_School_SubDistrict`,
            `Emergency_Communication_911_District`,
            `Emergency_Communication_911_SubDistrict`,
            `Enterprise_Zone_District`,
            `EXT_District`,
            `Exempted_Village_School_District`,
            `Facilities_Improvement_District`,
            `FIPS`,
            `Fire_District`,
            `Fire_Maintenance_District`,
            `Fire_Protection_District`,
            `Fire_Protection_SubDistrict`,
            `Fire_Protection_Tax_Measure_District`,
            `Fire_Service_Area_District`,
            `Fire_SubDistrict`,
            `Flood_Control_Zone`,
            `Forest_Preserve`,
            `Garbage_District`,
            `Geological_Hazard_Abatement_District`,
            `Hamlet_Community_Area`,
            `Health_District`,
            `High_School_District`,
            `High_School_SubDistrict`,
            `Hospital_SubDistrict`,
            `Improvement_Landowner_District`,
            `Independent_Fire_District`,
            `Irrigation_District`,
            `Irrigation_SubDistrict`,
            `Island`,
            `Judicial_Appellate_District`,
            `Judicial_Circuit_Court_District`,
            `Judicial_County_Board_of_Review_District`,
            `Judicial_County_Court_District`,
            `Judicial_District`,
            `Judicial_District_Court_District`,
            `Judicial_Family_Court_District`,
            `Judicial_Jury_District`,
            `Judicial_Juvenile_Court_District`,
            `Judicial_Magistrate_Division`,
            `Judicial_Municipal_Court_District`,
            `Judicial_Sub_Circuit_District`,
            `Judicial_Superior_Court_District`,
            `Judicial_Supreme_Court_District`,
            `Landscaping_and_Lighting_Assessment_District`,
            `Land_Commission`,
            `Law_Enforcement_District`,
            `Learning_Community_Coordinating_Council_District`,
            `Levee_District`,
            `Levee_Reconstruction_Assesment_District`,
            `Library_District`,
            `Library_Services_District`,
            `Library_SubDistrict`,
            `Lighting_District`,
            `Local_Hospital_District`,
            `Local_Park_District`,
            `Maintenance_District`,
            `Master_Plan_District`,
            `Memorial_District`,
            `Metro_Service_District`,
            `Metro_Service_Subdistrict`,
            `Metro_Transit_District`,
            `Metropolitan_Water_District`,
            `Middle_School_District`,
            `Mosquito_Abatement_District`,
            `Mountain_Water_District`,
            `Multi_township_Assessor`,
            `Municipal_Advisory_Council_District`,
            `Municipal_Utility_District`,
            `Municipal_Utility_SubDistrict`,
            `Municipal_Water_District`,
            `Municipal_Water_SubDistrict`,
            `Museum_District`,
            `Northeast_Soil_and_Water_District`,
            `Open_Space_District`,
            `Open_Space_SubDistrict`,
            `Other`,
            `Paramedic_District`,
            `Park_Commissioner_District`,
            `Park_District`,
            `Park_SubDistrict`,
            `Planning_Area_District`,
            `Police_District`,
            `Port_District`,
            `Port_SubDistrict`,
            `Power_District`,
            `Precinct`,
            `Proposed_City`,
            `Proposed_City_Commissioner_District`,
            `Proposed_Community_College`,
            `Proposed_District`,
            `Proposed_Elementary_School_District`,
            `Proposed_Fire_District`,
            `Proposed_Unified_School_District`,
            `Public_Airport_District`,
            `Public_Regulation_Commission`,
            `Public_Service_Commission_District`,
            `Public_Utility_District`,
            `Public_Utility_SubDistrict`,
            `Rapid_Transit_District`,
            `Rapid_Transit_SubDistrict`,
            `Reclamation_District`,
            `Recreation_District`,
            `Recreational_SubDistrict`,
            `Regional_Office_of_Education_District`,
            `Republican_Area`,
            `Republican_Convention_Member`,
            `Resort_Improvement_District`,
            `Resource_Conservation_District`,
            `River_Water_District`,
            `Road_Maintenance_District`,
            `Rural_Service_District`,
            `Sanitary_District`,
            `Sanitary_SubDistrict`,
            `School_Board_District`,
            `School_District`,
            `School_District_Vocational`,
            `School_Facilities_Improvement_District`,
            `School_Subdistrict`,
            `Service_Area_District`,
            `Sewer_District`,
            `Sewer_Maintenance_District`,
            `Sewer_SubDistrict`,
            `Snow_Removal_District`,
            `Special_Reporting_District`,
            `Special_Tax_District`,
            `State_House_District`,
            `State_Legislative_District`,
            `State_Senate_District`,
            `Storm_Water_District`,
            `Street_Lighting_District`,
            `Superintendent_of_Schools_District`,
            `TV_Translator_District`,
            `Town_Council`,
            `Town_District`,
            `Town_Ward`,
            `Township`,
            `Township_Ward`,
            `Transit_District`,
            `Transit_SubDistrict`,
            `TriCity_Service_District`,
            `US_Congressional_District`,
            `Unified_School_District`,
            `Unified_School_SubDistrict`,
            `Unincorporated_District`,
            `Unincorporated_Park_District`,
            `Unprotected_Fire_District`,
            `Ute_Creek_Soil_District`,
            `Vector_Control_District`,
            `Village`,
            `Village_Ward`,
            `Vote_By_Mail_Area`,
            `Wastewater_District`,
            `Water_Agency`,
            `Water_Agency_SubDistrict`,
            `Water_Conservation_District`,
            `Water_Conservation_SubDistrict`,
            `Water_Control_Water_Conservation`,
            `Water_Control_Water_Conservation_SubDistrict`,
            `Water_District`,
            `Water_Public_Utility_District`,
            `Water_Public_Utility_Subdistrict`,
            `Water_Replacement_District`,
            `Water_Replacement_SubDistrict`,
            `Water_SubDistrict`,
            `Weed_District`,

            -- Timestamps
            created_at,
            updated_at

        from source_voters
    )

select *
from deid_voters
