"""
False-negative analysis: find candidacy pairs that SHOULD match but aren't
being generated by the current blocking rules.

Approach:
1. Load data and build a "likely match" set using a very permissive cartesian
   join on (state, election_date, last_name) across sources — this is our
   approximate ground truth of plausible matches.
2. Run the current blocking rules to see which pairs they generate.
3. Find pairs in the ground truth that are NOT generated by blocking rules.
4. Analyze what's different about the missed pairs.

Usage:
    cd prototyping/entity_resolution
    uv run python scripts/05_false_negative_analysis.py
"""

import json
from pathlib import Path

import duckdb
import pandas as pd

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_DIR = SCRIPT_DIR.parent
DATA_DIR = PROJECT_DIR / "data"
RESULTS_DIR = PROJECT_DIR / "results"
INPUT_CSV = DATA_DIR / "input.csv"


def load_and_prepare() -> pd.DataFrame:
    df = pd.read_csv(INPUT_CSV, dtype=str)

    if "election_date" in df.columns:
        df["election_date"] = pd.to_datetime(
            df["election_date"], errors="coerce"
        ).dt.date.astype(str)
        df["election_date"] = df["election_date"].replace(
            {"NaT": None, "nan": None, "None": None}
        )

    df["first_name"] = df["first_name"].str.lower().str.strip()
    df["last_name"] = df["last_name"].str.lower().str.strip()

    if "first_name_aliases" in df.columns:
        df["first_name_aliases"] = df["first_name_aliases"].apply(
            lambda v: (
                json.loads(v)
                if isinstance(v, str)
                else v if isinstance(v, list) else [v]
            )
        )
    else:
        df["first_name_aliases"] = df["first_name"].apply(lambda n: [n])

    if "official_office_name" in df.columns:
        df["official_office_name"] = df["official_office_name"].str.lower().str.strip()

    if "district_identifier" in df.columns:
        df["district_identifier"] = (
            df["district_identifier"].str.lstrip("0").replace({"": "0"})
        )

    df["br_race_id_int"] = df["br_race_id"].where(
        df["br_race_id"].str.isnumeric().fillna(False), other=None
    )

    df = df.where(df.notna(), None)
    df = df.replace({"": None, "nan": None, "null": None})

    return df


def main():
    df = load_and_prepare()
    print(f"Loaded {len(df):,} rows")

    con = duckdb.connect()
    con.execute("CREATE TABLE records AS SELECT * FROM df")

    # Build a "ground truth" of plausible matches: cross-source pairs where
    # names are similar (JW >= 0.88 on last_name AND first_name matches or
    # aliases overlap or JW >= 0.88 on first_name).
    # This is intentionally very permissive to catch anything we might miss.
    print("\nBuilding plausible match set (permissive cross-source join)...")
    plausible = con.execute(
        """
        WITH br AS (
            SELECT * FROM records WHERE source_name = 'ballotready'
        ),
        ts AS (
            SELECT * FROM records WHERE source_name = 'techspeed'
        )
        SELECT
            br.unique_id AS br_id,
            ts.unique_id AS ts_id,
            br.first_name AS br_first,
            ts.first_name AS ts_first,
            br.last_name AS br_last,
            ts.last_name AS ts_last,
            br.state AS br_state,
            ts.state AS ts_state,
            br.election_date AS br_date,
            ts.election_date AS ts_date,
            br.official_office_name AS br_office,
            ts.official_office_name AS ts_office,
            br.district_identifier AS br_district,
            ts.district_identifier AS ts_district,
            br.br_race_id_int AS br_race_id,
            ts.br_race_id_int AS ts_race_id,
            br.email AS br_email,
            ts.email AS ts_email,
            br.phone AS br_phone,
            ts.phone AS ts_phone,
            jaro_winkler_similarity(br.last_name, ts.last_name) AS last_name_jw,
            jaro_winkler_similarity(br.first_name, ts.first_name) AS first_name_jw,
            jaro_winkler_similarity(br.official_office_name, ts.official_office_name) AS office_jw,
        FROM br
        JOIN ts ON br.state = ts.state
        WHERE jaro_winkler_similarity(br.last_name, ts.last_name) >= 0.88
          AND (
              jaro_winkler_similarity(br.first_name, ts.first_name) >= 0.88
              OR br.email = ts.email
              OR br.phone = ts.phone
          )
    """
    ).fetchdf()
    print(f"Plausible matches (name similar, same state): {len(plausible):,}")

    # Now simulate the current blocking rules to find which pairs are generated
    print("\nSimulating blocking rules...")

    # Rule 1: block_on("br_race_id_int")
    block1 = con.execute(
        """
        SELECT DISTINCT br.unique_id AS br_id, ts.unique_id AS ts_id
        FROM records br
        JOIN records ts ON br.br_race_id_int = ts.br_race_id_int
        WHERE br.source_name = 'ballotready' AND ts.source_name = 'techspeed'
          AND br.br_race_id_int IS NOT NULL
    """
    ).fetchdf()
    print(f"  block_on(br_race_id_int): {len(block1):,} pairs")

    # Rule 2: CustomRule - state + election_date + fuzzy office + last_name
    block2 = con.execute(
        """
        SELECT DISTINCT br.unique_id AS br_id, ts.unique_id AS ts_id
        FROM records br
        JOIN records ts
          ON br.state = ts.state
          AND br.election_date = ts.election_date
          AND jaro_winkler_similarity(br.official_office_name, ts.official_office_name) >= 0.88
          AND br.last_name = ts.last_name
        WHERE br.source_name = 'ballotready' AND ts.source_name = 'techspeed'
    """
    ).fetchdf()
    print(f"  CustomRule(state+date+office_jw+last): {len(block2):,} pairs")

    # Rule 3: block_on("state", "last_name", "election_date")
    block3 = con.execute(
        """
        SELECT DISTINCT br.unique_id AS br_id, ts.unique_id AS ts_id
        FROM records br
        JOIN records ts
          ON br.state = ts.state
          AND br.last_name = ts.last_name
          AND br.election_date = ts.election_date
        WHERE br.source_name = 'ballotready' AND ts.source_name = 'techspeed'
    """
    ).fetchdf()
    print(f"  block_on(state+last+date): {len(block3):,} pairs")

    # Rule 4: block_on("phone")
    block4 = con.execute(
        """
        SELECT DISTINCT br.unique_id AS br_id, ts.unique_id AS ts_id
        FROM records br
        JOIN records ts ON br.phone = ts.phone
        WHERE br.source_name = 'ballotready' AND ts.source_name = 'techspeed'
          AND br.phone IS NOT NULL
    """
    ).fetchdf()
    print(f"  block_on(phone): {len(block4):,} pairs")

    # Rule 5: block_on("email")
    block5 = con.execute(
        """
        SELECT DISTINCT br.unique_id AS br_id, ts.unique_id AS ts_id
        FROM records br
        JOIN records ts ON br.email = ts.email
        WHERE br.source_name = 'ballotready' AND ts.source_name = 'techspeed'
          AND br.email IS NOT NULL
    """
    ).fetchdf()
    print(f"  block_on(email): {len(block5):,} pairs")

    # Union all blocked pairs
    all_blocked = pd.concat([block1, block2, block3, block4, block5]).drop_duplicates()
    print(f"\n  Total unique blocked pairs: {len(all_blocked):,}")

    # Find plausible matches NOT covered by any blocking rule
    plausible_keys = set(zip(plausible["br_id"], plausible["ts_id"]))
    blocked_keys = set(zip(all_blocked["br_id"], all_blocked["ts_id"]))

    missed = plausible_keys - blocked_keys
    covered = plausible_keys & blocked_keys
    print(f"\n  Plausible matches covered by blocking: {len(covered):,}")
    print(f"  Plausible matches MISSED by blocking: {len(missed):,}")

    if len(missed) == 0:
        print("\nNo false negatives detected!")
        return

    # Analyze the missed pairs
    missed_df = plausible[
        plausible.apply(lambda r: (r["br_id"], r["ts_id"]) in missed, axis=1)
    ].copy()

    print(f"\n{'='*70}")
    print(f"MISSED PAIR ANALYSIS ({len(missed_df):,} pairs)")
    print(f"{'='*70}")

    # Why were they missed? Check each blocking rule condition
    missed_df["has_same_race_id"] = (
        missed_df["br_race_id"].notna()
        & missed_df["ts_race_id"].notna()
        & (missed_df["br_race_id"] == missed_df["ts_race_id"])
    )
    missed_df["has_same_state_date_last"] = (
        (missed_df["br_state"] == missed_df["ts_state"])
        & (missed_df["br_date"] == missed_df["ts_date"])
        & (missed_df["br_last"] == missed_df["ts_last"])
    )
    missed_df["has_same_phone"] = (
        missed_df["br_phone"].notna()
        & missed_df["ts_phone"].notna()
        & (missed_df["br_phone"] == missed_df["ts_phone"])
    )
    missed_df["has_same_email"] = (
        missed_df["br_email"].notna()
        & missed_df["ts_email"].notna()
        & (missed_df["br_email"] == missed_df["ts_email"])
    )
    missed_df["has_fuzzy_office_block"] = (
        (missed_df["br_state"] == missed_df["ts_state"])
        & (missed_df["br_date"] == missed_df["ts_date"])
        & (missed_df["office_jw"] >= 0.88)
        & (missed_df["br_last"] == missed_df["ts_last"])
    )

    # What's different?
    missed_df["same_date"] = missed_df["br_date"] == missed_df["ts_date"]
    missed_df["same_last_exact"] = missed_df["br_last"] == missed_df["ts_last"]
    missed_df["same_office_exact"] = missed_df["br_office"] == missed_df["ts_office"]

    print("\nWhy missed (counts):")
    print(f"  Different election_date: {(~missed_df['same_date']).sum():,}")
    print(f"  Different last_name (exact): {(~missed_df['same_last_exact']).sum():,}")
    print(f"  No shared br_race_id_int: {(~missed_df['has_same_race_id']).sum():,}")
    print(f"  No shared phone: {(~missed_df['has_same_phone']).sum():,}")
    print(f"  No shared email: {(~missed_df['has_same_email']).sum():,}")

    # The critical group: same date + fuzzy last name but not exact
    fuzzy_last_only = missed_df[
        missed_df["same_date"]
        & (~missed_df["same_last_exact"])
        & (missed_df["last_name_jw"] >= 0.88)
    ]
    print(f"\n  Same date + fuzzy last name (not exact): {len(fuzzy_last_only):,}")

    diff_date = missed_df[~missed_df["same_date"]]
    print(f"  Different date (same person, diff election): {len(diff_date):,}")

    # Show examples of missed pairs
    print("\n--- Examples of missed pairs (up to 30) ---")
    for i, (_, row) in enumerate(
        missed_df.sort_values("last_name_jw", ascending=False).head(30).iterrows()
    ):
        print(
            f"\n  #{i+1}: last_jw={row['last_name_jw']:.3f}, first_jw={row['first_name_jw']:.3f}, office_jw={row['office_jw']:.3f}"
        )
        print(
            f"    Name: '{row['br_first']} {row['br_last']}' vs '{row['ts_first']} {row['ts_last']}'"
        )
        print(f"    State: {row['br_state']} vs {row['ts_state']}")
        print(f"    Date: {row['br_date']} vs {row['ts_date']}")
        print(f"    Office: '{row['br_office']}' vs '{row['ts_office']}'")
        print(f"    District: '{row['br_district']}' vs '{row['ts_district']}'")
        print(f"    Race ID: {row['br_race_id']} vs {row['ts_race_id']}")
        print(f"    Email: {row['br_email']} vs {row['ts_email']}")
        print(f"    Phone: {row['br_phone']} vs {row['ts_phone']}")

    # Save for review
    missed_df.to_csv(RESULTS_DIR / "missed_by_blocking.csv", index=False)
    print(f"\nFull missed pairs saved to {RESULTS_DIR / 'missed_by_blocking.csv'}")


if __name__ == "__main__":
    main()
