"""
Audit false negatives: find input records that didn't match but plausibly should have.

Scans singleton (unmatched) records from the clustered output and uses lightweight
heuristics to find candidate pairs that the model may have missed — either because
they weren't generated by blocking rules, or because the match probability fell
below the clustering threshold.

For the sake of safety, we'll implement some simple fuzzy-matching logic to
ensure we're catching as many potential false-negatives as possible.

Usage:
    cd entity_resolution
    uv run python scripts/audit_false_negatives.py --results-dir results/
    uv run python scripts/audit_false_negatives.py --results-dir results/ --sample 30
"""

from pathlib import Path

import click
import pandas as pd
from rapidfuzz.distance import JaroWinkler

DISPLAY_COLS = [
    "unique_id",
    "source_name",
    "first_name",
    "last_name",
    "party",
    "email",
    "phone",
    "state",
    "election_date",
    "official_office_name",
    "district_identifier",
    "candidate_office",
    "br_race_id",
]


def _name_similar(a: str | None, b: str | None, threshold: float = 0.88) -> bool:
    """Check if two names are similar using JW similarity or exact match."""
    if pd.isna(a) or pd.isna(b):
        return False
    a, b = str(a).lower().strip(), str(b).lower().strip()
    if a == b:
        return True
    return JaroWinkler.similarity(a, b) >= threshold


def run_false_negatives(
    input_df: pd.DataFrame,
    pairwise_df: pd.DataFrame,
    clustered_df: pd.DataFrame,
    results_dir: Path,
    sample_n: int = 20,
) -> pd.DataFrame:
    """Find suspicious non-matches and write audit CSV."""
    # Find singletons — records in clusters of size 1 (unmatched)
    cluster_sizes = clustered_df.groupby("cluster_id").size()
    singleton_clusters = cluster_sizes[cluster_sizes == 1].index
    singletons = clustered_df[clustered_df["cluster_id"].isin(singleton_clusters)]
    print(f"Total clustered records: {len(clustered_df):,}")
    print(f"Singleton (unmatched) records: {len(singletons):,}")

    providers = sorted(input_df["source_name"].unique())
    print(f"Providers: {providers}")

    # Check if suspicious pairs were generated but fell below the clustering threshold
    pairwise_ids = set()
    if len(pairwise_df) > 0 and "unique_id_l" in pairwise_df.columns:
        pairwise_ids = set(zip(pairwise_df["unique_id_l"], pairwise_df["unique_id_r"]))

    # For each singleton, look for plausible matches in other providers
    # using lightweight heuristics: same state + same election_date + similar last_name
    suspicious_pairs = []
    singleton_sample = singletons.sample(
        n=min(sample_n * 5, len(singletons)), random_state=42
    )

    # Pre-group input_df for O(1) candidate lookups instead of repeated boolean indexing
    candidate_groups = dict(input_df.groupby(["source_name", "state", "election_date"]))

    for _, singleton in singleton_sample.iterrows():
        s_provider = singleton["source_name"]
        s_state = singleton.get("state")
        s_date = singleton.get("election_date")
        s_last = singleton.get("last_name")

        if pd.isna(s_state) or pd.isna(s_last):
            continue

        # Look for candidates in other providers with same state + election date
        for other_provider in providers:
            if other_provider == s_provider:
                continue

            candidates = candidate_groups.get((other_provider, s_state, s_date))
            if candidates is None:
                continue

            for _, cand in candidates.iterrows():
                if not _name_similar(s_last, cand.get("last_name")):
                    continue

                # Check if first name also plausibly matches
                first_ok = _name_similar(
                    singleton.get("first_name"),
                    cand.get("first_name"),
                    threshold=0.85,
                )
                email_ok = (
                    singleton.get("email")
                    and cand.get("email")
                    and singleton["email"] == cand["email"]
                )
                phone_ok = (
                    singleton.get("phone")
                    and cand.get("phone")
                    and singleton["phone"] == cand["phone"]
                )

                if not (first_ok or email_ok or phone_ok):
                    continue

                # This looks like it should have matched — flag it
                pair_key = (singleton["unique_id"], cand["unique_id"])
                was_generated = (
                    pair_key in pairwise_ids
                    or (pair_key[1], pair_key[0]) in pairwise_ids
                )

                row = {"was_in_pairwise_predictions": was_generated}
                for col in DISPLAY_COLS:
                    row[f"{col}_l"] = singleton.get(col)
                    row[f"{col}_r"] = cand.get(col)
                suspicious_pairs.append(row)

        if len(suspicious_pairs) >= sample_n:
            break

    out_df = pd.DataFrame(suspicious_pairs[:sample_n])

    if len(out_df) == 0:
        print("\nNo suspicious non-matches found in sampled singletons.")
        return out_df

    out_path = results_dir / "audit_false_negatives.csv"
    out_df.to_csv(out_path, index=False)

    # Diagnostics
    in_pw = out_df["was_in_pairwise_predictions"].sum()
    not_in_pw = len(out_df) - in_pw
    print(f"\nSuspicious non-matches found: {len(out_df)}")
    print(
        f"  Were in pairwise predictions (model scored but below cluster threshold): {in_pw}"
    )
    print(f"  NOT in pairwise predictions (blocking rules missed them): {not_in_pw}")
    print(f"\nWritten to {out_path}")

    return out_df


@click.command()
@click.option(
    "--results-dir",
    required=True,
    type=click.Path(exists=True, file_okay=False, path_type=Path),
    help="Directory containing match results.",
)
@click.option(
    "--sample",
    "sample_n",
    default=20,
    type=int,
    help="Number of suspicious pairs to find.",
)
def main(results_dir: Path, sample_n: int) -> None:
    """Find plausible matches that the model missed."""
    input_df = pd.read_parquet(results_dir / "input.parquet")
    clustered_df = pd.read_csv(results_dir / "clustered_candidacies.csv")
    pairwise_path = results_dir / "pairwise_predictions.csv"
    pairwise_df = (
        pd.read_csv(pairwise_path) if pairwise_path.exists() else pd.DataFrame()
    )
    run_false_negatives(input_df, pairwise_df, clustered_df, results_dir, sample_n)


if __name__ == "__main__":
    main()
