-- BallotReady pass-through. Grain: one row per office-holder term.
-- Mart-layer `unique` test on gp_elected_official_id will catch any future
-- provider union that's added without a corresponding dedup step.
select
    gp_elected_official_id,
    br_office_holder_id,
    br_position_id,
    first_name,
    last_name,
    middle_name,
    suffix,
    full_name,
    email,
    phone,
    office_phone,
    central_phone,
    position_name,
    normalized_position_name,
    candidate_office,
    office_level,
    office_type,
    state,
    city,
    district,
    term_start_date,
    term_end_date,
    is_appointed,
    is_judicial,
    is_vacant,
    is_off_cycle,
    party_affiliation,
    website_url,
    linkedin_url,
    facebook_url,
    twitter_url,
    mailing_address_line_1,
    mailing_address_line_2,
    mailing_city,
    mailing_state,
    mailing_zip,
    br_geo_id,
    br_position_tier,
    candidate_id_source,
    created_at,
    updated_at
from {{ ref("int__civics_elected_official_ballotready") }}
