{{
    config(
        materialized="incremental",
        unique_key="LALVOTERID",
        on_schema_change="append_new_columns",
        auto_liquid_cluster=True,
        tags=["mart", "people_api", "voter"],
    )
}}

with
    updated_voters as (
        select
            -- Voter Information / Demographics
            {{ generate_salted_uuid(fields=["LALVOTERID"], salt="l2") }} as id,
            `LALVOTERID`,
            state_postal_code as `State`,
            `Voters_Active` as `Active`,
            `Voters_StateVoterID` as `StateVoterID`,
            `Voters_CountyVoterID` as `CountyVoterID`,
            `VoterTelephones_LandlineFormatted`,
            `VoterTelephones_LandlineConfidenceCode`,
            `VoterTelephones_CellPhoneFormatted`,
            `VoterTelephones_CellConfidenceCode`,
            `Voters_FirstName` as `FirstName`,
            `Voters_MiddleName` as `MiddleName`,
            `Voters_LastName` as `LastName`,
            `Voters_NameSuffix` as `NameSuffix`,
            `Residence_Addresses_AddressLine`,
            `Residence_Addresses_ExtraAddressLine`,
            `Residence_Addresses_City`,
            `Residence_Addresses_State`,
            `Residence_Addresses_Zip`,
            `Residence_Addresses_ZipPlus4`,
            `Residence_Addresses_DPBC`,
            try_cast(
                `Residence_Addresses_CheckDigit` as int
            ) as `Residence_Addresses_CheckDigit`,
            `Residence_Addresses_HouseNumber`,
            try_cast(
                `Residence_Addresses_PrefixDirection` as int
            ) as `Residence_Addresses_PrefixDirection`,
            `Residence_Addresses_StreetName`,
            `Residence_Addresses_Designator`,
            try_cast(
                `Residence_Addresses_SuffixDirection` as int
            ) as `Residence_Addresses_SuffixDirection`,
            `Residence_Addresses_ApartmentNum`,
            `Residence_Addresses_ApartmentType`,
            `Residence_Addresses_CassErrStatCode`,
            `Voters_SequenceZigZag` as `SequenceZigZag`,
            `Voters_SequenceOddEven` as `SequenceOddEven`,
            `Residence_Addresses_Latitude`,
            `Residence_Addresses_Longitude`,
            cast(null as string) as `Residence_Addresses_GeoHash`,
            `Residence_Addresses_LatLongAccuracy`,
            `Residence_HHParties_Description`,
            `Mailing_Addresses_AddressLine`,
            `Mailing_Addresses_ExtraAddressLine`,
            `Mailing_Addresses_City`,
            `Mailing_Addresses_State`,
            `Mailing_Addresses_Zip`,
            `Mailing_Addresses_ZipPlus4`,
            `Mailing_Addresses_DPBC`,
            try_cast(
                `Mailing_Addresses_CheckDigit` as int
            ) as `Mailing_Addresses_CheckDigit`,
            `Mailing_Addresses_HouseNumber`,
            try_cast(
                `Mailing_Addresses_PrefixDirection` as int
            ) as `Mailing_Addresses_PrefixDirection`,
            `Mailing_Addresses_StreetName`,
            `Mailing_Addresses_Designator`,
            try_cast(
                `Mailing_Addresses_SuffixDirection` as int
            ) as `Mailing_Addresses_SuffixDirection`,
            `Mailing_Addresses_ApartmentNum`,
            `Mailing_Addresses_ApartmentType`,
            `Mailing_Addresses_CassErrStatCode`,
            `Mailing_Families_FamilyID`,
            try_cast(null as int) as `Mailing_Families_HHCount`,
            cast(null as string) as `Mailing_HHGender_Description`,
            cast(null as string) as `Mailing_HHParties_Description`,
            cast(`Voters_Age` as string) as `Age`,
            try_cast(`Voters_Age` as int) as `Age_Int`,
            `Voters_Gender` as `Gender`,
            cast(null as string) as `DateConfidence_Description`,
            `Parties_Description`,
            `VoterParties_Change_Changed_Party`,
            `Ethnic_Description`,
            `EthnicGroups_EthnicGroup1Desc`,
            `CountyEthnic_LALEthnicCode`,
            `CountyEthnic_Description`,
            cast(null as string) as `Religions_Description`,
            `Voters_CalculatedRegDate` as `CalculatedRegDate`,
            `Voters_OfficialRegDate` as `OfficialRegDate`,
            `Voters_PlaceOfBirth` as `PlaceOfBirth`,
            cast(null as string) as `Languages_Description`,
            `AbsenteeTypes_Description`,
            cast(null as string) as `MilitaryStatus_Description`,
            cast(null as string) as `MaritalStatus_Description`,
            `Voters_MovedFrom_State` as `MovedFrom_State`,
            `Voters_MovedFrom_Date` as `MovedFrom_Date`,
            `Voters_MovedFrom_Party_Description` as `MovedFrom_Party_Description`,

            -- Voter Turnout
            `Voters_VotingPerformanceEvenYearGeneral`
            as `VotingPerformanceEvenYearGeneral`,
            `Voters_VotingPerformanceEvenYearPrimary`
            as `VotingPerformanceEvenYearPrimary`,
            `Voters_VotingPerformanceEvenYearGeneralAndPrimary`
            as `VotingPerformanceEvenYearGeneralAndPrimary`,
            `Voters_VotingPerformanceMinorElection` as `VotingPerformanceMinorElection`,
            `General_2026`,
            `Primary_2026`,
            `OtherElection_2026`,
            `AnyElection_2025`,
            `General_2024`,
            `Primary_2024`,
            `PresidentialPrimary_2024`,
            `OtherElection_2024`,
            `AnyElection_2023`,
            `General_2022`,
            `Primary_2022`,
            `OtherElection_2022`,
            `AnyElection_2021`,
            `General_2020`,
            `Primary_2020`,
            `PresidentialPrimary_2020`,
            `OtherElection_2020`,
            `AnyElection_2019`,
            `General_2018`,
            `Primary_2018`,
            `OtherElection_2018`,
            `AnyElection_2017`,
            `General_2016`,
            `Primary_2016`,
            `PresidentialPrimary_2016`,
            `OtherElection_2016`,

            -- Districts
            `US_Congressional_District`,
            `AddressDistricts_Change_Changed_CD`,
            `State_Senate_District`,
            `AddressDistricts_Change_Changed_SD`,
            `State_House_District`,
            `AddressDistricts_Change_Changed_HD`,
            `State_Legislative_District`,
            `AddressDistricts_Change_Changed_LD`,
            `County`,
            `Voters_FIPS` as `FIPS`,
            `AddressDistricts_Change_Changed_County`,
            `Precinct`,
            `County_Legislative_District`,
            `City`,
            `City_Council_Commissioner_District`,
            `County_Commissioner_District`,
            `County_Supervisorial_District`,
            `City_Mayoral_District`,
            `Town_District`,
            `Town_Council`,
            `Village`,
            `Township`,
            `Borough`,
            `Hamlet_Community_Area`,
            `City_Ward`,
            `Town_Ward`,
            `Township_Ward`,
            `Village_Ward`,
            `Borough_Ward`,
            `Board_of_Education_District`,
            `Board_of_Education_SubDistrict`,
            `City_School_District`,
            `College_Board_District`,
            `Community_College_Commissioner_District`,
            `Community_College_SubDistrict`,
            `County_Board_of_Education_District`,
            `County_Board_of_Education_SubDistrict`,
            `County_Community_College_District`,
            `County_Superintendent_of_Schools_District`,
            `County_Unified_School_District`,
            `District_Attorney`,
            `Education_Commission_District`,
            `Educational_Service_District`,
            `Election_Commissioner_District`,
            `Elementary_School_District`,
            `Elementary_School_SubDistrict`,
            `Exempted_Village_School_District`,
            `High_School_District`,
            `High_School_SubDistrict`,
            `Judicial_Appellate_District`,
            `Judicial_Circuit_Court_District`,
            `Judicial_County_Board_of_Review_District`,
            `Judicial_County_Court_District`,
            `Judicial_District`,
            `Judicial_District_Court_District`,
            `Judicial_Family_Court_District`,
            `Judicial_Jury_District`,
            `Judicial_Juvenile_Court_District`,
            `Judicial_Magistrate_Division`,
            `Judicial_Sub_Circuit_District`,
            `Judicial_Superior_Court_District`,
            `Judicial_Supreme_Court_District`,
            `Middle_School_District`,
            cast(null as string) as `Municipal_Court_District`,
            `Proposed_City_Commissioner_District`,
            `Proposed_Elementary_School_District`,
            `Proposed_Unified_School_District`,
            `Regional_Office_of_Education_District`,
            `School_Board_District`,
            `School_District`,
            `School_District_Vocational`,
            `School_Facilities_Improvement_District`,
            `School_Subdistrict`,
            `Service_Area_District`,
            `Superintendent_of_Schools_District`,
            `Unified_School_District`,
            `Unified_School_SubDistrict`,
            `Coast_Water_District`,
            `Consolidated_Water_District`,
            `County_Water_District`,
            `County_Water_Landowner_District`,
            `County_Water_SubDistrict`,
            `Metropolitan_Water_District`,
            `Mountain_Water_District`,
            `Municipal_Water_District`,
            `Municipal_Water_SubDistrict`,
            `River_Water_District`,
            `Water_Agency`,
            `Water_Agency_SubDistrict`,
            `Water_Conservation_District`,
            `Water_Conservation_SubDistrict`,
            cast(null as string) as `Water_Control__Water_Conservation`,
            cast(null as string) as `Water_Control__Water_Conservation_SubDistrict`,
            `Water_District`,
            `Water_Public_Utility_District`,
            `Water_Public_Utility_Subdistrict`,
            `Water_Replacement_District`,
            `Water_Replacement_SubDistrict`,
            `Water_SubDistrict`,
            `County_Fire_District`,
            `Fire_District`,
            `Fire_Maintenance_District`,
            `Fire_Protection_District`,
            `Fire_Protection_SubDistrict`,
            `Fire_Protection_Tax_Measure_District`,
            `Fire_Service_Area_District`,
            `Fire_SubDistrict`,
            `Independent_Fire_District`,
            `Proposed_Fire_District`,
            `Unprotected_Fire_District`,
            `Bay_Area_Rapid_Transit`,
            `Metro_Transit_District`,
            `Rapid_Transit_District`,
            `Rapid_Transit_SubDistrict`,
            `Transit_District`,
            `Transit_SubDistrict`,
            `Community_Service_District`,
            `Community_Service_SubDistrict`,
            `County_Service_Area`,
            `County_Service_Area_SubDistrict`,
            `TriCity_Service_District`,
            `Library_Services_District`,
            `Airport_District`,
            `Annexation_District`,
            `Aquatic_Center_District`,
            `Aquatic_District`,
            `Assessment_District`,
            `Bonds_District`,
            `Career_Center`,
            `Cemetery_District`,
            `Central_Committee_District`,
            `Chemical_Control_District`,
            `Committee_Super_District`,
            `Communications_District`,
            `Community_College_At_Large`,
            `Community_Council_District`,
            `Community_Council_SubDistrict`,
            `Community_Facilities_District`,
            `Community_Facilities_SubDistrict`,
            `Community_Hospital_District`,
            `Community_Planning_Area`,
            `Congressional_Township`,
            `Conservation_District`,
            `Conservation_SubDistrict`,
            `Control_Zone_District`,
            `Corrections_District`,
            `County_Hospital_District`,
            `County_Library_District`,
            `County_Memorial_District`,
            `County_Paramedic_District`,
            `County_Sewer_District`,
            `Democratic_Convention_Member`,
            `Democratic_Zone`,
            `Designated_Market_Area_DMA`,
            `Drainage_District`,
            `Educational_Service_Subdistrict`,
            `Emergency_Communication_911_District`,
            `Emergency_Communication_911_SubDistrict`,
            `Enterprise_Zone_District`,
            `EXT_District`,
            `Facilities_Improvement_District`,
            `Flood_Control_Zone`,
            `Forest_Preserve`,
            `Garbage_District`,
            `Geological_Hazard_Abatement_District`,
            `Health_District`,
            `Hospital_SubDistrict`,
            `Improvement_Landowner_District`,
            `Irrigation_District`,
            `Irrigation_SubDistrict`,
            `Island`,
            `Land_Commission`,
            cast(null as string) as `Landscaping_And_Lighting_Assessment_Distric`,
            `Law_Enforcement_District`,
            `Learning_Community_Coordinating_Council_District`,
            `Levee_District`,
            `Levee_Reconstruction_Assesment_District`,
            `Library_District`,
            `Library_SubDistrict`,
            `Lighting_District`,
            `Local_Hospital_District`,
            `Local_Park_District`,
            `Maintenance_District`,
            `Master_Plan_District`,
            `Memorial_District`,
            `Metro_Service_District`,
            `Metro_Service_Subdistrict`,
            `Mosquito_Abatement_District`,
            `Multi_township_Assessor`,
            `Municipal_Advisory_Council_District`,
            `Municipal_Utility_District`,
            `Municipal_Utility_SubDistrict`,
            `Museum_District`,
            cast(null as string) as `Northeast_Soil_and_Water_District`,
            `Open_Space_District`,
            `Open_Space_SubDistrict`,
            `Other`,
            `Paramedic_District`,
            `Park_Commissioner_District`,
            `Park_District`,
            `Park_SubDistrict`,
            `Planning_Area_District`,
            `Police_District`,
            `Port_District`,
            `Port_SubDistrict`,
            `Power_District`,
            `Proposed_City`,
            `Proposed_Community_College`,
            `Proposed_District`,
            `Public_Airport_District`,
            `Public_Regulation_Commission`,
            `Public_Service_Commission_District`,
            `Public_Utility_District`,
            `Public_Utility_SubDistrict`,
            `Reclamation_District`,
            `Recreation_District`,
            `Recreational_SubDistrict`,
            `Republican_Area`,
            `Republican_Convention_Member`,
            `Resort_Improvement_District`,
            `Resource_Conservation_District`,
            `Road_Maintenance_District`,
            `Rural_Service_District`,
            `Sanitary_District`,
            `Sanitary_SubDistrict`,
            `Sewer_District`,
            `Sewer_Maintenance_District`,
            `Sewer_SubDistrict`,
            `Snow_Removal_District`,
            cast(null as string) as `Soil_And_Water_District`,
            cast(null as string) as `Soil_And_Water_District_At_Large`,
            `Special_Reporting_District`,
            `Special_Tax_District`,
            `Storm_Water_District`,
            `Street_Lighting_District`,
            `TV_Translator_District`,
            `Unincorporated_District`,
            `Unincorporated_Park_District`,
            `Ute_Creek_Soil_District`,
            `Vector_Control_District`,
            `Vote_By_Mail_Area`,
            `Wastewater_District`,
            `Weed_District`
        from {{ ref("int__l2_nationwide_uniform") }}
        where
            1 = 1
            {% if is_incremental() %}
                and loaded_at > (select max(updated_at) from {{ this }})
            {% endif %}
    ),
    /*
        Note that here we need to list each column individually since we need to
        explicitly case protect each column name with backticks to match the Voter table
        in the people-api schema.
    */
    final as (
        select
            tbl_updated.id,
            tbl_updated.`LALVOTERID`,
            tbl_updated.`State`,
            tbl_updated.`Active`,
            tbl_updated.`StateVoterID`,
            tbl_updated.`CountyVoterID`,
            tbl_updated.`VoterTelephones_LandlineFormatted`,
            tbl_updated.`VoterTelephones_LandlineConfidenceCode`,
            tbl_updated.`VoterTelephones_CellPhoneFormatted`,
            tbl_updated.`VoterTelephones_CellConfidenceCode`,
            tbl_updated.`FirstName`,
            tbl_updated.`MiddleName`,
            tbl_updated.`LastName`,
            tbl_updated.`NameSuffix`,
            tbl_updated.`Residence_Addresses_AddressLine`,
            tbl_updated.`Residence_Addresses_ExtraAddressLine`,
            tbl_updated.`Residence_Addresses_City`,
            tbl_updated.`Residence_Addresses_State`,
            tbl_updated.`Residence_Addresses_Zip`,
            tbl_updated.`Residence_Addresses_ZipPlus4`,
            tbl_updated.`Residence_Addresses_DPBC`,
            tbl_updated.`Residence_Addresses_CheckDigit`,
            tbl_updated.`Residence_Addresses_HouseNumber`,
            tbl_updated.`Residence_Addresses_PrefixDirection`,
            tbl_updated.`Residence_Addresses_StreetName`,
            tbl_updated.`Residence_Addresses_Designator`,
            tbl_updated.`Residence_Addresses_SuffixDirection`,
            tbl_updated.`Residence_Addresses_ApartmentNum`,
            tbl_updated.`Residence_Addresses_ApartmentType`,
            tbl_updated.`Residence_Addresses_CassErrStatCode`,
            tbl_updated.`SequenceZigZag`,
            tbl_updated.`SequenceOddEven`,
            tbl_updated.`Residence_Addresses_Latitude`,
            tbl_updated.`Residence_Addresses_Longitude`,
            tbl_updated.`Residence_Addresses_GeoHash`,
            tbl_updated.`Residence_Addresses_LatLongAccuracy`,
            tbl_updated.`Residence_HHParties_Description`,
            tbl_updated.`Mailing_Addresses_AddressLine`,
            tbl_updated.`Mailing_Addresses_ExtraAddressLine`,
            tbl_updated.`Mailing_Addresses_City`,
            tbl_updated.`Mailing_Addresses_State`,
            tbl_updated.`Mailing_Addresses_Zip`,
            tbl_updated.`Mailing_Addresses_ZipPlus4`,
            tbl_updated.`Mailing_Addresses_DPBC`,
            tbl_updated.`Mailing_Addresses_CheckDigit`,
            tbl_updated.`Mailing_Addresses_HouseNumber`,
            tbl_updated.`Mailing_Addresses_PrefixDirection`,
            tbl_updated.`Mailing_Addresses_StreetName`,
            tbl_updated.`Mailing_Addresses_Designator`,
            tbl_updated.`Mailing_Addresses_SuffixDirection`,
            tbl_updated.`Mailing_Addresses_ApartmentNum`,
            tbl_updated.`Mailing_Addresses_ApartmentType`,
            tbl_updated.`Mailing_Addresses_CassErrStatCode`,
            tbl_updated.`Mailing_Families_FamilyID`,
            tbl_updated.`Mailing_Families_HHCount`,
            tbl_updated.`Mailing_HHGender_Description`,
            tbl_updated.`Mailing_HHParties_Description`,
            tbl_updated.`Age`,
            tbl_updated.`Age_Int`,
            tbl_updated.`Gender`,
            tbl_updated.`DateConfidence_Description`,
            tbl_updated.`Parties_Description`,
            tbl_updated.`VoterParties_Change_Changed_Party`,
            tbl_updated.`Ethnic_Description`,
            tbl_updated.`EthnicGroups_EthnicGroup1Desc`,
            tbl_updated.`CountyEthnic_LALEthnicCode`,
            tbl_updated.`CountyEthnic_Description`,
            tbl_updated.`Religions_Description`,
            tbl_updated.`CalculatedRegDate`,
            tbl_updated.`OfficialRegDate`,
            tbl_updated.`PlaceOfBirth`,
            tbl_updated.`Languages_Description`,
            tbl_updated.`AbsenteeTypes_Description`,
            tbl_updated.`MilitaryStatus_Description`,
            tbl_updated.`MaritalStatus_Description`,
            tbl_updated.`MovedFrom_State`,
            tbl_updated.`MovedFrom_Date`,
            tbl_updated.`MovedFrom_Party_Description`,

            -- Voter Turnout
            tbl_updated.`VotingPerformanceEvenYearGeneral`,
            tbl_updated.`VotingPerformanceEvenYearPrimary`,
            tbl_updated.`VotingPerformanceEvenYearGeneralAndPrimary`,
            tbl_updated.`VotingPerformanceMinorElection`,
            tbl_updated.`General_2026`,
            tbl_updated.`Primary_2026`,
            tbl_updated.`OtherElection_2026`,
            tbl_updated.`AnyElection_2025`,
            tbl_updated.`General_2024`,
            tbl_updated.`Primary_2024`,
            tbl_updated.`PresidentialPrimary_2024`,
            tbl_updated.`OtherElection_2024`,
            tbl_updated.`AnyElection_2023`,
            tbl_updated.`General_2022`,
            tbl_updated.`Primary_2022`,
            tbl_updated.`OtherElection_2022`,
            tbl_updated.`AnyElection_2021`,
            tbl_updated.`General_2020`,
            tbl_updated.`Primary_2020`,
            tbl_updated.`PresidentialPrimary_2020`,
            tbl_updated.`OtherElection_2020`,
            tbl_updated.`AnyElection_2019`,
            tbl_updated.`General_2018`,
            tbl_updated.`Primary_2018`,
            tbl_updated.`OtherElection_2018`,
            tbl_updated.`AnyElection_2017`,
            tbl_updated.`General_2016`,
            tbl_updated.`Primary_2016`,
            tbl_updated.`PresidentialPrimary_2016`,
            tbl_updated.`OtherElection_2016`,

            -- Districts
            tbl_updated.`US_Congressional_District`,
            tbl_updated.`AddressDistricts_Change_Changed_CD`,
            tbl_updated.`State_Senate_District`,
            tbl_updated.`AddressDistricts_Change_Changed_SD`,
            tbl_updated.`State_House_District`,
            tbl_updated.`AddressDistricts_Change_Changed_HD`,
            tbl_updated.`State_Legislative_District`,
            tbl_updated.`AddressDistricts_Change_Changed_LD`,
            tbl_updated.`County`,
            tbl_updated.`FIPS`,
            tbl_updated.`AddressDistricts_Change_Changed_County`,
            tbl_updated.`Precinct`,
            tbl_updated.`County_Legislative_District`,
            tbl_updated.`City`,
            tbl_updated.`City_Council_Commissioner_District`,
            tbl_updated.`County_Commissioner_District`,
            tbl_updated.`County_Supervisorial_District`,
            tbl_updated.`City_Mayoral_District`,
            tbl_updated.`Town_District`,
            tbl_updated.`Town_Council`,
            tbl_updated.`Village`,
            tbl_updated.`Township`,
            tbl_updated.`Borough`,
            tbl_updated.`Hamlet_Community_Area`,
            tbl_updated.`City_Ward`,
            tbl_updated.`Town_Ward`,
            tbl_updated.`Township_Ward`,
            tbl_updated.`Village_Ward`,
            tbl_updated.`Borough_Ward`,
            tbl_updated.`Board_of_Education_District`,
            tbl_updated.`Board_of_Education_SubDistrict`,
            tbl_updated.`City_School_District`,
            tbl_updated.`College_Board_District`,
            tbl_updated.`Community_College_Commissioner_District`,
            tbl_updated.`Community_College_SubDistrict`,
            tbl_updated.`County_Board_of_Education_District`,
            tbl_updated.`County_Board_of_Education_SubDistrict`,
            tbl_updated.`County_Community_College_District`,
            tbl_updated.`County_Superintendent_of_Schools_District`,
            tbl_updated.`County_Unified_School_District`,
            tbl_updated.`District_Attorney`,
            tbl_updated.`Education_Commission_District`,
            tbl_updated.`Educational_Service_District`,
            tbl_updated.`Election_Commissioner_District`,
            tbl_updated.`Elementary_School_District`,
            tbl_updated.`Elementary_School_SubDistrict`,
            tbl_updated.`Exempted_Village_School_District`,
            tbl_updated.`High_School_District`,
            tbl_updated.`High_School_SubDistrict`,
            tbl_updated.`Judicial_Appellate_District`,
            tbl_updated.`Judicial_Circuit_Court_District`,
            tbl_updated.`Judicial_County_Board_of_Review_District`,
            tbl_updated.`Judicial_County_Court_District`,
            tbl_updated.`Judicial_District`,
            tbl_updated.`Judicial_District_Court_District`,
            tbl_updated.`Judicial_Family_Court_District`,
            tbl_updated.`Judicial_Jury_District`,
            tbl_updated.`Judicial_Juvenile_Court_District`,
            tbl_updated.`Judicial_Magistrate_Division`,
            tbl_updated.`Judicial_Sub_Circuit_District`,
            tbl_updated.`Judicial_Superior_Court_District`,
            tbl_updated.`Judicial_Supreme_Court_District`,
            tbl_updated.`Middle_School_District`,
            tbl_updated.`Municipal_Court_District`,
            tbl_updated.`Proposed_City_Commissioner_District`,
            tbl_updated.`Proposed_Elementary_School_District`,
            tbl_updated.`Proposed_Unified_School_District`,
            tbl_updated.`Regional_Office_of_Education_District`,
            tbl_updated.`School_Board_District`,
            tbl_updated.`School_District`,
            tbl_updated.`School_District_Vocational`,
            tbl_updated.`School_Facilities_Improvement_District`,
            tbl_updated.`School_Subdistrict`,
            tbl_updated.`Service_Area_District`,
            tbl_updated.`Superintendent_of_Schools_District`,
            tbl_updated.`Unified_School_District`,
            tbl_updated.`Unified_School_SubDistrict`,
            tbl_updated.`Coast_Water_District`,
            tbl_updated.`Consolidated_Water_District`,
            tbl_updated.`County_Water_District`,
            tbl_updated.`County_Water_Landowner_District`,
            tbl_updated.`County_Water_SubDistrict`,
            tbl_updated.`Metropolitan_Water_District`,
            tbl_updated.`Mountain_Water_District`,
            tbl_updated.`Municipal_Water_District`,
            tbl_updated.`Municipal_Water_SubDistrict`,
            tbl_updated.`River_Water_District`,
            tbl_updated.`Water_Agency`,
            tbl_updated.`Water_Agency_SubDistrict`,
            tbl_updated.`Water_Conservation_District`,
            tbl_updated.`Water_Conservation_SubDistrict`,
            tbl_updated.`Water_Control__Water_Conservation`,
            tbl_updated.`Water_Control__Water_Conservation_SubDistrict`,
            tbl_updated.`Water_District`,
            tbl_updated.`Water_Public_Utility_District`,
            tbl_updated.`Water_Public_Utility_Subdistrict`,
            tbl_updated.`Water_Replacement_District`,
            tbl_updated.`Water_Replacement_SubDistrict`,
            tbl_updated.`Water_SubDistrict`,
            tbl_updated.`County_Fire_District`,
            tbl_updated.`Fire_District`,
            tbl_updated.`Fire_Maintenance_District`,
            tbl_updated.`Fire_Protection_District`,
            tbl_updated.`Fire_Protection_SubDistrict`,
            tbl_updated.`Fire_Protection_Tax_Measure_District`,
            tbl_updated.`Fire_Service_Area_District`,
            tbl_updated.`Fire_SubDistrict`,
            tbl_updated.`Independent_Fire_District`,
            tbl_updated.`Proposed_Fire_District`,
            tbl_updated.`Unprotected_Fire_District`,
            tbl_updated.`Bay_Area_Rapid_Transit`,
            tbl_updated.`Metro_Transit_District`,
            tbl_updated.`Rapid_Transit_District`,
            tbl_updated.`Rapid_Transit_SubDistrict`,
            tbl_updated.`Transit_District`,
            tbl_updated.`Transit_SubDistrict`,
            tbl_updated.`Community_Service_District`,
            tbl_updated.`Community_Service_SubDistrict`,
            tbl_updated.`County_Service_Area`,
            tbl_updated.`County_Service_Area_SubDistrict`,
            tbl_updated.`TriCity_Service_District`,
            tbl_updated.`Library_Services_District`,
            tbl_updated.`Airport_District`,
            tbl_updated.`Annexation_District`,
            tbl_updated.`Aquatic_Center_District`,
            tbl_updated.`Aquatic_District`,
            tbl_updated.`Assessment_District`,
            tbl_updated.`Bonds_District`,
            tbl_updated.`Career_Center`,
            tbl_updated.`Cemetery_District`,
            tbl_updated.`Central_Committee_District`,
            tbl_updated.`Chemical_Control_District`,
            tbl_updated.`Committee_Super_District`,
            tbl_updated.`Communications_District`,
            tbl_updated.`Community_College_At_Large`,
            tbl_updated.`Community_Council_District`,
            tbl_updated.`Community_Council_SubDistrict`,
            tbl_updated.`Community_Facilities_District`,
            tbl_updated.`Community_Facilities_SubDistrict`,
            tbl_updated.`Community_Hospital_District`,
            tbl_updated.`Community_Planning_Area`,
            tbl_updated.`Congressional_Township`,
            tbl_updated.`Conservation_District`,
            tbl_updated.`Conservation_SubDistrict`,
            tbl_updated.`Control_Zone_District`,
            tbl_updated.`Corrections_District`,
            tbl_updated.`County_Hospital_District`,
            tbl_updated.`County_Library_District`,
            tbl_updated.`County_Memorial_District`,
            tbl_updated.`County_Paramedic_District`,
            tbl_updated.`County_Sewer_District`,
            tbl_updated.`Democratic_Convention_Member`,
            tbl_updated.`Democratic_Zone`,
            tbl_updated.`Designated_Market_Area_DMA`,
            tbl_updated.`Drainage_District`,
            tbl_updated.`Educational_Service_Subdistrict`,
            tbl_updated.`Emergency_Communication_911_District`,
            tbl_updated.`Emergency_Communication_911_SubDistrict`,
            tbl_updated.`Enterprise_Zone_District`,
            tbl_updated.`EXT_District`,
            tbl_updated.`Facilities_Improvement_District`,
            tbl_updated.`Flood_Control_Zone`,
            tbl_updated.`Forest_Preserve`,
            tbl_updated.`Garbage_District`,
            tbl_updated.`Geological_Hazard_Abatement_District`,
            tbl_updated.`Health_District`,
            tbl_updated.`Hospital_SubDistrict`,
            tbl_updated.`Improvement_Landowner_District`,
            tbl_updated.`Irrigation_District`,
            tbl_updated.`Irrigation_SubDistrict`,
            tbl_updated.`Island`,
            tbl_updated.`Land_Commission`,
            tbl_updated.`Landscaping_And_Lighting_Assessment_Distric`,
            tbl_updated.`Law_Enforcement_District`,
            tbl_updated.`Learning_Community_Coordinating_Council_District`,
            tbl_updated.`Levee_District`,
            tbl_updated.`Levee_Reconstruction_Assesment_District`,
            tbl_updated.`Library_District`,
            tbl_updated.`Library_SubDistrict`,
            tbl_updated.`Lighting_District`,
            tbl_updated.`Local_Hospital_District`,
            tbl_updated.`Local_Park_District`,
            tbl_updated.`Maintenance_District`,
            tbl_updated.`Master_Plan_District`,
            tbl_updated.`Memorial_District`,
            tbl_updated.`Metro_Service_District`,
            tbl_updated.`Metro_Service_Subdistrict`,
            tbl_updated.`Mosquito_Abatement_District`,
            tbl_updated.`Multi_township_Assessor`,
            tbl_updated.`Municipal_Advisory_Council_District`,
            tbl_updated.`Municipal_Utility_District`,
            tbl_updated.`Municipal_Utility_SubDistrict`,
            tbl_updated.`Museum_District`,
            tbl_updated.`Northeast_Soil_and_Water_District`,
            tbl_updated.`Open_Space_District`,
            tbl_updated.`Open_Space_SubDistrict`,
            tbl_updated.`Other`,
            tbl_updated.`Paramedic_District`,
            tbl_updated.`Park_Commissioner_District`,
            tbl_updated.`Park_District`,
            tbl_updated.`Park_SubDistrict`,
            tbl_updated.`Planning_Area_District`,
            tbl_updated.`Police_District`,
            tbl_updated.`Port_District`,
            tbl_updated.`Port_SubDistrict`,
            tbl_updated.`Power_District`,
            tbl_updated.`Proposed_City`,
            tbl_updated.`Proposed_Community_College`,
            tbl_updated.`Proposed_District`,
            tbl_updated.`Public_Airport_District`,
            tbl_updated.`Public_Regulation_Commission`,
            tbl_updated.`Public_Service_Commission_District`,
            tbl_updated.`Public_Utility_District`,
            tbl_updated.`Public_Utility_SubDistrict`,
            tbl_updated.`Reclamation_District`,
            tbl_updated.`Recreation_District`,
            tbl_updated.`Recreational_SubDistrict`,
            tbl_updated.`Republican_Area`,
            tbl_updated.`Republican_Convention_Member`,
            tbl_updated.`Resort_Improvement_District`,
            tbl_updated.`Resource_Conservation_District`,
            tbl_updated.`Road_Maintenance_District`,
            tbl_updated.`Rural_Service_District`,
            tbl_updated.`Sanitary_District`,
            tbl_updated.`Sanitary_SubDistrict`,
            tbl_updated.`Sewer_District`,
            tbl_updated.`Sewer_Maintenance_District`,
            tbl_updated.`Sewer_SubDistrict`,
            tbl_updated.`Snow_Removal_District`,
            tbl_updated.`Soil_And_Water_District`,
            tbl_updated.`Soil_And_Water_District_At_Large`,
            tbl_updated.`Special_Reporting_District`,
            tbl_updated.`Special_Tax_District`,
            tbl_updated.`Storm_Water_District`,
            tbl_updated.`Street_Lighting_District`,
            tbl_updated.`TV_Translator_District`,
            tbl_updated.`Unincorporated_District`,
            tbl_updated.`Unincorporated_Park_District`,
            tbl_updated.`Ute_Creek_Soil_District`,
            tbl_updated.`Vector_Control_District`,
            tbl_updated.`Vote_By_Mail_Area`,
            tbl_updated.`Wastewater_District`,
            tbl_updated.`Weed_District`,
            {% if is_incremental() %}
                -- For incremental runs, preserve existing created_at for existing
                -- records,
                -- set current timestamp for new records
                coalesce(tbl_existing.created_at, current_timestamp()) as created_at,
            {% else %}
                -- For full refresh, set created_at to current timestamp for all records
                current_timestamp() as created_at,
            {% endif %}
            -- Always set updated_at to current timestamp
            current_timestamp() as updated_at
        from updated_voters as tbl_updated
        {% if is_incremental() %}
            left join
                {{ this }} as tbl_existing
                on tbl_updated.lalvoterid = tbl_existing.lalvoterid
        {% endif %}
    )

select *
from final
