with
    source as (select * from {{ source("airbyte_source", "amplitude_api_events") }}),
    renamed as (
        select
            {{ adapter.quote("_airbyte_raw_id") }},
            {{ adapter.quote("_airbyte_extracted_at") }},
            {{ adapter.quote("_airbyte_meta") }},
            {{ adapter.quote("_airbyte_generation_id") }},
            {{ adapter.quote("app") }},
            {{ adapter.quote("dma") }},
            {{ adapter.quote("adid") }},
            {{ adapter.quote("city") }},
            {{ adapter.quote("data") }},
            {{ adapter.quote("idfa") }},
            {{ adapter.quote("plan") }},
            {{ adapter.quote("uuid") }},
            {{ adapter.quote("groups") }},
            {{ adapter.quote("paying") }},
            {{ adapter.quote("region") }},
            {{ adapter.quote("_schema") }},
            {{ adapter.quote("country") }},
            {{ adapter.quote("library") }},
            {{ adapter.quote("os_name") }},
            {{ adapter.quote("user_id") }},
            {{ adapter.quote("event_id") }},
            {{ adapter.quote("language") }},
            {{ adapter.quote("platform") }},
            {{ adapter.quote("data_type") }},
            {{ adapter.quote("device_id") }},
            {{ adapter.quote("source_id") }},
            {{ adapter.quote("_insert_id") }},
            {{ adapter.quote("event_time") }},
            {{ adapter.quote("event_type") }},
            {{ adapter.quote("ip_address") }},
            {{ adapter.quote("os_version") }},
            {{ adapter.quote("partner_id") }},
            {{ adapter.quote("session_id") }},
            {{ adapter.quote("_insert_key") }},
            {{ adapter.quote("device_type") }},
            {{ adapter.quote("sample_rate") }},
            {{ adapter.quote("amplitude_id") }},
            {{ adapter.quote("device_brand") }},
            {{ adapter.quote("device_model") }},
            {{ adapter.quote("location_lat") }},
            {{ adapter.quote("location_lng") }},
            {{ adapter.quote("version_name") }},
            {{ adapter.quote("device_family") }},
            {{ adapter.quote("start_version") }},
            {{ adapter.quote("device_carrier") }},
            {{ adapter.quote("processed_time") }},
            {{ adapter.quote("user_properties") }},
            {{ adapter.quote("event_properties") }},
            {{ adapter.quote("group_properties") }},
            {{ adapter.quote("client_event_time") }},
            {{ adapter.quote("client_upload_time") }},
            {{ adapter.quote("server_upload_time") }},
            {{ adapter.quote("user_creation_time") }},
            {{ adapter.quote("device_manufacturer") }},
            {{ adapter.quote("amplitude_event_type") }},
            {{ adapter.quote("is_attribution_event") }},
            {{ adapter.quote("server_received_time") }},
            {{ adapter.quote("global_user_properties") }},
            {{ adapter.quote("amplitude_attribution_ids") }}

        from source
    )
select *
from renamed
