name: airflow
on:
  pull_request:
    paths: ['airflow/**', '.github/workflows/airflow.yml']
  push:
    branches: [main]
    paths: ['airflow/**', '.github/workflows/airflow.yml']
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: airflow
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install poetry
        run: pipx install poetry
      - name: Install deps
        run: poetry install
      - name: Pytest
        run: poetry run pytest
