name: airflow
on:
  pull_request:
    paths: ['airflow/**', '.github/workflows/airflow.yml', '.github/workflows/uv-subproject.yml']
  push:
    branches: [main]
    paths: ['airflow/**', '.github/workflows/airflow.yml', '.github/workflows/uv-subproject.yml']
jobs:
  test:
    uses: ./.github/workflows/uv-subproject.yml
    with:
      directory: airflow
      mypy-targets: astro/dags astro/tests astro/include/custom_functions
