name: dbt
on:
  pull_request:
    paths: ['dbt/**', '.github/workflows/dbt.yml']
  push:
    branches: [main]
    paths: ['dbt/**', '.github/workflows/dbt.yml']
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dbt
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'
          cache-dependency-path: dbt/poetry.lock
      - name: Install deps
        run: poetry install
      - name: Pytest
        run: poetry run pytest
