name: dbt
on:
  pull_request:
    paths: ['dbt/**', '.github/workflows/dbt.yml', '.github/workflows/uv-subproject.yml']
  push:
    branches: [main]
    paths: ['dbt/**', '.github/workflows/dbt.yml', '.github/workflows/uv-subproject.yml']
jobs:
  test:
    uses: ./.github/workflows/uv-subproject.yml
    with:
      directory: dbt
      mypy-targets: tests
